namespace LostFound.Domain.Entities;

public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public DateTime? UpdatedAtUtc { get; set; } }
public enum AccountType { Person, Organization }
public enum ItemType { Lost, Found }
public enum ItemStatus { Active, Matched, Claimed, ReturnInProgress, Returned, Closed, Rejected, Removed }
public enum ClaimStatus { Pending, UnderReview, Accepted, Rejected, Cancelled, Completed }
public enum ExchangeStatus { Pending, Ready, Completed, Expired, Cancelled }
public enum MatchStatus { Suggested=0, Dismissed=1, Confirmed=2, Candidate=3, Viewed=4, Rejected=5, Expired=6 }
public enum ReportStatus { Open, UnderReview, Resolved, Dismissed, Escalated }
public enum ModerationOutcome { Allowed, Flagged, Blocked, ReviewRequired }
public enum MatchingJobStatus { Pending, Processing, Completed, Failed }
public sealed class Category : Entity { public string Slug { get; set; } = ""; public string NameKey { get; set; } = ""; public int SortOrder { get; set; } public bool IsActive { get; set; } = true; public List<Subcategory> Subcategories { get; set; } = []; public List<Item> Items { get; set; } = []; }
public sealed class Subcategory : Entity { public Guid CategoryId { get; set; } public Category Category { get; set; } = null!; public string Slug { get; set; } = ""; public string NameKey { get; set; } = ""; public bool IsActive { get; set; } = true; public List<Item> Items { get; set; } = []; }
public sealed class Item : Entity { public Guid OwnerId { get; set; } public Guid CategoryId { get; set; } public Category Category { get; set; } = null!; public Guid? SubcategoryId { get; set; } public Subcategory? Subcategory { get; set; } public ItemType Type { get; set; } public ItemStatus Status { get; set; } = ItemStatus.Active; public string Title { get; set; } = ""; public string Description { get; set; } = ""; public string? Brand { get; set; } public string? Color { get; set; } public string Location { get; set; } = ""; public double? Latitude { get; set; } public double? Longitude { get; set; } public DateTime OccurredAtUtc { get; set; } public decimal? RewardAmount { get; set; } public int ViewCount { get; set; } public bool IsDeleted { get; set; } public List<ItemPhoto> Photos { get; set; } = []; public List<ItemAttribute> Attributes { get; set; } = []; public List<Claim> Claims { get; set; } = []; public List<ClaimQuestion> ClaimQuestions { get; set; } = []; }
public sealed class ItemPhoto : Entity { public Guid ItemId { get; set; } public Item Item { get; set; } = null!; public string StorageKey { get; set; } = ""; public string ContentType { get; set; } = ""; public long SizeBytes { get; set; } public int SortOrder { get; set; } }
public sealed class ItemAttribute : Entity { public Guid ItemId { get; set; } public Item Item { get; set; } = null!; public string Key { get; set; } = ""; public string Value { get; set; } = ""; }
public sealed class Favorite : Entity { public Guid UserId { get; set; } public Guid ItemId { get; set; } public Item Item { get; set; } = null!; }
public sealed class RefreshToken : Entity { public Guid UserId { get; set; } public string TokenHash { get; set; } = ""; public DateTime ExpiresAtUtc { get; set; } public DateTime? RevokedAtUtc { get; set; } public Guid? ReplacedByTokenId { get; set; } }
public sealed class Claim : Entity { public Guid ItemId { get; set; } public Item Item { get; set; } = null!; public Guid ClaimantId { get; set; } public ClaimStatus Status { get; set; } = ClaimStatus.Pending; public DateTime? ReviewedAtUtc { get; set; } public DateTime? CompletedAtUtc { get; set; } public Guid ConcurrencyToken { get; set; } = Guid.NewGuid(); public List<ClaimAnswer> Answers { get; set; } = []; public Exchange? Exchange { get; set; } }
public sealed class ClaimQuestion : Entity { public Guid ItemId { get; set; } public Item Item { get; set; } = null!; public string Prompt { get; set; } = ""; public string ExpectedAnswerHash { get; set; } = ""; public int SortOrder { get; set; } public bool IsActive { get; set; } = true; }
public sealed class ClaimAnswer : Entity { public Guid ClaimId { get; set; } public Claim Claim { get; set; } = null!; public Guid QuestionId { get; set; } public ClaimQuestion Question { get; set; } = null!; public string QuestionSnapshot { get; set; } = ""; public string AnswerCiphertext { get; set; } = ""; }
public sealed class ItemMatch : Entity { public Guid LostItemId { get; set; } public Item LostItem { get; set; } = null!; public Guid FoundItemId { get; set; } public Item FoundItem { get; set; } = null!; public decimal MatchScore { get; set; } public MatchStatus Status { get; set; } = MatchStatus.Candidate; public string ScoreBreakdownJson { get; set; } = "{}"; public string EngineVersion { get; set; } = "deterministic-v1"; public DateTime? NotifiedAtUtc { get; set; } public string? NotificationVersion { get; set; } public Guid ConcurrencyToken { get; set; } = Guid.NewGuid(); }
public sealed class Conversation : Entity { public Guid? ItemId { get; set; } public Item? Item { get; set; } public string? DirectKey { get; set; } public List<ConversationParticipant> Participants { get; set; } = []; public List<Message> Messages { get; set; } = []; }
public sealed class ConversationParticipant : Entity { public Guid ConversationId { get; set; } public Conversation Conversation { get; set; } = null!; public Guid UserId { get; set; } public DateTime? LastReadAtUtc { get; set; } }
public sealed class Message : Entity { public Guid ConversationId { get; set; } public Conversation Conversation { get; set; } = null!; public Guid SenderId { get; set; } public string Body { get; set; } = ""; public bool IsDeleted { get; set; } }
public sealed class Exchange : Entity { public Guid ClaimId { get; set; } public Claim Claim { get; set; } = null!; public Guid ItemId { get; set; } public Item Item { get; set; } = null!; public Guid OwnerId { get; set; } public Guid ClaimantId { get; set; } public ExchangeStatus Status { get; set; } = ExchangeStatus.Pending; public string CodeHash { get; set; } = ""; public string CodeSalt { get; set; } = ""; public DateTime? CodeIssuedAtUtc { get; set; } public DateTime? ExpiresAtUtc { get; set; } public DateTime? LockedUntilUtc { get; set; } public DateTime? CompletedAtUtc { get; set; } public int FailedAttempts { get; set; } public int GenerationCount { get; set; } public Guid ConcurrencyToken { get; set; } = Guid.NewGuid(); }
public sealed class Rating : Entity { public Guid ExchangeId { get; set; } public Exchange Exchange { get; set; } = null!; public Guid ReviewerId { get; set; } public Guid RevieweeId { get; set; } public int Score { get; set; } public string? Review { get; set; } }
public sealed class Report : Entity { public Guid ReporterId { get; set; } public Guid? ItemId { get; set; } public Item? Item { get; set; } public Guid? ReportedUserId { get; set; } public Guid? MessageId { get; set; } public Message? Message { get; set; } public string Reason { get; set; } = ""; public string? Details { get; set; } public string Severity { get; set; } = "normal"; public ReportStatus Status { get; set; } public Guid? AssignedModeratorId { get; set; } public string? InternalNotes { get; set; } public Guid ConcurrencyToken { get; set; } = Guid.NewGuid(); }
public sealed class Notification : Entity { public Guid UserId { get; set; } public string Type { get; set; } = ""; public string PayloadJson { get; set; } = "{}"; public DateTime? ReadAtUtc { get; set; } }
public sealed class QrToken : Entity { public Guid OwnerId { get; set; } public Guid? ItemId { get; set; } public Item? Item { get; set; } public string Label { get; set; } = ""; public string? Description { get; set; } public string PublicTokenHash { get; set; } = ""; public bool IsActive { get; set; } = true; public DateTime? RevokedAtUtc { get; set; } public List<QrScan> Scans { get; set; } = []; }
public sealed class QrScan : Entity { public Guid QrTokenId { get; set; } public QrToken QrToken { get; set; } = null!; public string? CoarseLocation { get; set; } public bool ContactRequested { get; set; } public string? UserAgentFamily { get; set; } }
public sealed class AuditEvent : Entity { public Guid? ActorId { get; set; } public string Action { get; set; } = ""; public string EntityType { get; set; } = ""; public Guid? EntityId { get; set; } public string MetadataJson { get; set; } = "{}"; }
public sealed class UserBlock : Entity { public Guid BlockerId { get; set; } public Guid BlockedId { get; set; } }
public sealed class ModerationRecord : Entity { public string TargetType { get; set; } = ""; public Guid TargetId { get; set; } public ModerationOutcome Outcome { get; set; } public string ReasonCode { get; set; } = ""; public string PolicyVersion { get; set; } = "local-v1"; public Guid? ActorId { get; set; } public string? InternalNotes { get; set; } public string CorrelationId { get; set; } = ""; }
public sealed class MatchingJob : Entity { public Guid ItemId { get; set; } public MatchingJobStatus Status { get; set; }=MatchingJobStatus.Pending; public int AttemptCount { get; set; } public DateTime NextAttemptAtUtc { get; set; }=DateTime.UtcNow; public DateTime? LockedAtUtc { get; set; } public string EngineVersion { get; set; }="deterministic-v1"; public string? LastErrorCode { get; set; } public Guid ConcurrencyToken { get; set; }=Guid.NewGuid(); }
