using System.Globalization;
using System.Text;
using Asp.Versioning;
using FluentValidation;
using LostFound.Infrastructure.Identity;
using LostFound.Infrastructure.Persistence;
using LostFound.Application.Abstractions;
using LostFound.Infrastructure.Storage;
using LostFound.Infrastructure.Qr;
using LostFound.Infrastructure.Matching;
using LostFound.Api.Hubs;
using System.Threading.RateLimiting;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.DataProtection;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi;
using Serilog;
using Serilog.Events;
var builder = WebApplication.CreateBuilder(args);
builder.Host.UseSerilog((context, config) => config.ReadFrom.Configuration(context.Configuration).Enrich.FromLogContext().WriteTo.Console());
var connection = builder.Configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("ConnectionStrings__DefaultConnection is required.");
builder.Services.AddDbContext<LostFoundDbContext>(o => o.UseNpgsql(connection));
var runtimeRoot=builder.Configuration["Storage:RuntimeRoot"]??builder.Environment.ContentRootPath;var uploadsPath=Path.Combine(runtimeRoot,"uploads");var keyPath=builder.Configuration["DataProtection:KeyPath"]??Path.Combine(runtimeRoot,"keys");
builder.Services.AddScoped<IFileStorageService>(_ => new LocalFileStorageService(runtimeRoot));
builder.Services.AddSingleton<IQrCodeRenderer,QrCodeRenderer>();
builder.Services.Configure<MatchingOptions>(builder.Configuration.GetSection("Matching")); builder.Services.Configure<MatchingJobOptions>(builder.Configuration.GetSection("MatchingJobs")); builder.Services.AddScoped<IItemMatchingService,DeterministicMatchingService>(); builder.Services.AddScoped<IMatchingJobQueue,PostgresMatchingJobQueue>(); builder.Services.AddHostedService<MatchingJobWorker>(); builder.Services.AddSingleton<IAiMatchingProvider,NoOpAiMatchingProvider>(); builder.Services.AddSingleton<ITextModerationService,LocalTextModerationService>(); builder.Services.AddSingleton<IImageModerationService,ManualReviewImageModerationService>();
builder.Services.AddDataProtection().PersistKeysToFileSystem(new DirectoryInfo(keyPath)).SetApplicationName("LostFound.Production"); builder.Services.Configure<ForwardedHeadersOptions>(o=>{o.ForwardedHeaders=ForwardedHeaders.XForwardedFor|ForwardedHeaders.XForwardedProto|ForwardedHeaders.XForwardedHost;o.KnownProxies.Clear();o.KnownIPNetworks.Clear();o.KnownProxies.Add(IPAddress.Loopback);o.KnownProxies.Add(IPAddress.IPv6Loopback);}); builder.Services.AddSignalR(); builder.Services.AddRateLimiter(o=>{o.RejectionStatusCode=StatusCodes.Status429TooManyRequests;o.AddPolicy("auth",context=>RateLimitPartition.GetFixedWindowLimiter(context.Connection.RemoteIpAddress?.ToString()??"unknown",_=>new FixedWindowRateLimiterOptions{PermitLimit=10,Window=TimeSpan.FromMinutes(1),QueueLimit=0}));o.AddPolicy("ownership",context=>RateLimitPartition.GetFixedWindowLimiter(context.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value??context.Connection.RemoteIpAddress?.ToString()??"unknown",_=>new FixedWindowRateLimiterOptions{PermitLimit=12,Window=TimeSpan.FromMinutes(1),QueueLimit=0}));o.AddPolicy("publicQr",context=>RateLimitPartition.GetFixedWindowLimiter(context.Connection.RemoteIpAddress?.ToString()??"unknown",_=>new FixedWindowRateLimiterOptions{PermitLimit=30,Window=TimeSpan.FromMinutes(1),QueueLimit=0}));}); 
builder.Services.AddIdentityCore<ApplicationUser>(o => { o.Password.RequiredLength = 8; o.Password.RequireUppercase = true; o.Password.RequireLowercase = true; o.Password.RequireDigit = true; o.Password.RequireNonAlphanumeric = false; o.SignIn.RequireConfirmedEmail = true; }).AddRoles<IdentityRole<Guid>>().AddEntityFrameworkStores<LostFoundDbContext>().AddDefaultTokenProviders();
var issuer = builder.Configuration["Jwt:Issuer"] ?? "lostfound-api"; var audience = builder.Configuration["Jwt:Audience"] ?? "lostfound-clients"; var key = builder.Configuration["Jwt:SigningKey"];
if (string.IsNullOrWhiteSpace(key) || key.Length < 32) throw new InvalidOperationException("Jwt__SigningKey of at least 32 characters is required.");
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o => {
 o.TokenValidationParameters = new() { ValidateIssuer = true, ValidIssuer = issuer, ValidateAudience = true, ValidAudience = audience, ValidateLifetime = true, ValidateIssuerSigningKey = true, IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key)), ClockSkew = TimeSpan.FromSeconds(30) };
 o.Events = new JwtBearerEvents { OnMessageReceived = context => { var token=context.Request.Query["access_token"]; if(!string.IsNullOrEmpty(token)&&context.HttpContext.Request.Path.StartsWithSegments("/hubs/communication"))context.Token=token; return Task.CompletedTask; } };
});
builder.Services.AddAuthorization(o => { o.AddPolicy("Moderator", p => p.RequireRole("Moderator", "Admin")); o.AddPolicy("Admin", p => p.RequireRole("Admin")); });
builder.Services.AddApiVersioning(o => { o.DefaultApiVersion = new(1, 0); o.AssumeDefaultVersionWhenUnspecified = true; o.ReportApiVersions = true; }).AddApiExplorer(o => { o.GroupNameFormat = "'v'VVV"; o.SubstituteApiVersionInUrl = true; });
builder.Services.AddProblemDetails(); builder.Services.AddExceptionHandler<GlobalExceptionHandler>(); builder.Services.AddControllers(); builder.Services.AddLocalization(); builder.Services.AddValidatorsFromAssemblyContaining<LostFound.Application.Abstractions.IItemMatchingService>();
builder.Services.Configure<RequestLocalizationOptions>(o => { var cultures = new[] { new CultureInfo("ka"), new CultureInfo("en"), new CultureInfo("ru") }; o.DefaultRequestCulture = new("ka"); o.SupportedCultures = cultures; o.SupportedUICultures = cultures; });
builder.Services.AddCors(o => o.AddPolicy("Frontend", p => p.WithOrigins(builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>() ?? []).AllowAnyHeader().AllowAnyMethod()));
builder.Services.AddHealthChecks().AddDbContextCheck<LostFoundDbContext>("postgresql",tags:["ready"]); builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(o => { o.SwaggerDoc("v1", new OpenApiInfo { Title = "Lost & Found API", Version = "v1" }); o.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme { Type = SecuritySchemeType.Http, Scheme = "bearer", BearerFormat = "JWT" }); });
var app = builder.Build(); app.UseForwardedHeaders(); app.UseExceptionHandler(); app.UseRequestLocalization(); app.UseSerilogRequestLogging(o=>o.GetLevel=(context,_,exception)=>context.Request.Path.Value?.Contains("/qr/",StringComparison.OrdinalIgnoreCase)==true?LogEventLevel.Verbose:exception is null?LogEventLevel.Information:LogEventLevel.Error); if (app.Environment.IsDevelopment()) { app.UseSwagger(); app.UseSwaggerUI(); } Directory.CreateDirectory(uploadsPath);Directory.CreateDirectory(keyPath); app.UseStaticFiles(new StaticFileOptions { FileProvider = new Microsoft.Extensions.FileProviders.PhysicalFileProvider(uploadsPath), RequestPath = "/uploads" }); app.UseHttpsRedirection(); app.UseCors("Frontend"); app.UseRateLimiter(); app.UseAuthentication(); app.Use(async(context,next)=>{context.Response.Headers["X-Correlation-ID"]=context.TraceIdentifier;if(context.User.Identity?.IsAuthenticated==true&&Guid.TryParse(context.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value,out var uid)){await using var scope=context.RequestServices.CreateAsyncScope();var database=scope.ServiceProvider.GetRequiredService<LostFoundDbContext>();var restricted=await database.Users.AsNoTracking().AnyAsync(x=>x.Id==uid&&(x.IsPermanentlyBlocked||(x.IsSuspended&&(x.SuspendedUntilUtc==null||x.SuspendedUntilUtc>DateTime.UtcNow))));if(restricted){context.Response.StatusCode=403;await context.Response.WriteAsJsonAsync(new ProblemDetails{Status=403,Title="Account restricted",Type="https://httpstatuses.com/403"});return;}}await next();}); app.UseAuthorization(); app.MapControllers(); app.MapHub<CommunicationHub>("/hubs/communication"); app.MapHealthChecks("/health/live",new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions{Predicate=_=>false});app.MapHealthChecks("/health/ready",new Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckOptions{Predicate=x=>x.Tags.Contains("ready")}); app.MapHealthChecks("/health"); app.Run();
public partial class Program { }
