using System.Net;using System.Net.WebSockets;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using LostFound.Domain.Entities;
using LostFound.Infrastructure.Identity;
using LostFound.Infrastructure.Persistence;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

var baseUrl=Environment.GetEnvironmentVariable("PHASE5_BASE_URL")??"http://127.0.0.1:5099";
var connection=Environment.GetEnvironmentVariable("ConnectionStrings__DefaultConnection")??throw new InvalidOperationException("Database connection is required.");
var options=new DbContextOptionsBuilder<LostFoundDbContext>().UseNpgsql(connection).Options;
await using var db=new LostFoundDbContext(options);
using var http=new HttpClient{BaseAddress=new Uri(baseUrl)};
var run=$"p5-{Guid.NewGuid():N}";var password=$"V!{Guid.NewGuid():N}z9";
var users=new Dictionary<string,(Guid Id,string Token,string Refresh)>(StringComparer.Ordinal);
var items=new List<Guid>();var conversations=new List<Guid>();

void Check(bool condition,string name){if(!condition)throw new InvalidOperationException($"FAILED: {name}");Console.WriteLine($"PASS {name}");}
async Task<(HttpStatusCode Status,string Body)> Send(HttpMethod method,string path,string? token=null,object? body=null){using var request=new HttpRequestMessage(method,path);if(token is not null)request.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token);if(body is not null)request.Content=JsonContent.Create(body);using var response=await http.SendAsync(request);return(response.StatusCode,await response.Content.ReadAsStringAsync());}
Guid IdFromToken(string token){var encoded=token.Split('.')[1].Replace('-','+').Replace('_','/');encoded=encoded.PadRight(encoded.Length+(4-encoded.Length%4)%4,'=');using var json=JsonDocument.Parse(Convert.FromBase64String(encoded));return Guid.Parse(json.RootElement.GetProperty("sub").GetString()!);}
string Prop(string json,string name){using var d=JsonDocument.Parse(json);return d.RootElement.GetProperty(name).GetString()!;}
Guid GuidProp(string json,string name)=>Guid.Parse(Prop(json,name));
async Task<(Guid,string,string)> Register(string label){var email=$"{run}-{label}@example.invalid";var r=await Send(HttpMethod.Post,"/api/v1/auth/register",body:new{accountType=0,email,password,firstName="Phase",lastName=label,organizationName=(string?)null,responsiblePerson=(string?)null,phoneNumber=(string?)null});Check(r.Status==HttpStatusCode.OK,$"register {label}");var token=Prop(r.Body,"accessToken");var value=(IdFromToken(token),token,Prop(r.Body,"refreshToken"));users[label]=value;return value;}
async Task<(string Token,string Refresh)> Login(string label){var email=$"{run}-{label}@example.invalid";var r=await Send(HttpMethod.Post,"/api/v1/auth/login",body:new{email,password});Check(r.Status==HttpStatusCode.OK,$"login {label} with role");return(Prop(r.Body,"accessToken"),Prop(r.Body,"refreshToken"));}

try{
 foreach(var label in new[]{"lost","found","unrelated","moderator","admin"})await Register(label);
 foreach(var roleName in new[]{"Moderator","Admin"})if(!await db.Roles.AnyAsync(x=>x.NormalizedName==roleName.ToUpperInvariant()))db.Roles.Add(new IdentityRole<Guid>{Name=roleName,NormalizedName=roleName.ToUpperInvariant()});await db.SaveChangesAsync();
 var moderatorRole=await db.Roles.SingleAsync(x=>x.NormalizedName=="MODERATOR");var adminRole=await db.Roles.SingleAsync(x=>x.NormalizedName=="ADMIN");db.UserRoles.Add(new IdentityUserRole<Guid>{UserId=users["moderator"].Id,RoleId=moderatorRole.Id});db.UserRoles.Add(new IdentityUserRole<Guid>{UserId=users["admin"].Id,RoleId=adminRole.Id});await db.SaveChangesAsync();
 var refreshed=await Send(HttpMethod.Post,"/api/v1/auth/refresh",body:new{refreshToken=users["lost"].Refresh});Check(refreshed.Status==HttpStatusCode.OK,"refresh token rotates successfully");users["lost"]=(users["lost"].Id,Prop(refreshed.Body,"accessToken"),Prop(refreshed.Body,"refreshToken"));var negotiate=await Send(HttpMethod.Post,"/hubs/communication/negotiate?negotiateVersion=1",users["lost"].Token);Check(negotiate.Status==HttpStatusCode.OK,"SignalR negotiation through proxy");var connectionToken=Prop(negotiate.Body,"connectionToken");using(var socket=new ClientWebSocket()){var wsBase=baseUrl.Replace("http://","ws://").Replace("https://","wss://").TrimEnd('/');await socket.ConnectAsync(new Uri($"{wsBase}/hubs/communication?id={Uri.EscapeDataString(connectionToken)}&access_token={Uri.EscapeDataString(users["lost"].Token)}"),CancellationToken.None);var handshake=Encoding.UTF8.GetBytes("{\"protocol\":\"json\",\"version\":1}\u001e");await socket.SendAsync(handshake,WebSocketMessageType.Text,true,CancellationToken.None);var buffer=new byte[256];var received=await socket.ReceiveAsync(buffer,CancellationToken.None);Check(received.Count>0&&Encoding.UTF8.GetString(buffer,0,received.Count).StartsWith("{}"),"SignalR WebSocket handshake through proxy");await socket.CloseAsync(WebSocketCloseStatus.NormalClosure,"verified",CancellationToken.None);}var moderatorLogin=await Login("moderator");var adminLogin=await Login("admin");users["moderator"]=(users["moderator"].Id,moderatorLogin.Token,moderatorLogin.Refresh);users["admin"]=(users["admin"].Id,adminLogin.Token,adminLogin.Refresh);
 var occurred=DateTime.UtcNow.AddHours(-3);object ItemBody(int type,string title)=>new{type,title,description="black nylon backpack with books and a reusable water bottle",categoryId="33333333-3333-3333-3333-333333333333",subcategoryId="aaaaaaaa-0000-0000-0000-000000000007",brand="Herschel",color="Black",location="Vake Park, Tbilisi",latitude=41.708,longitude=44.751,occurredAtUtc=occurred,rewardAmount=(decimal?)null,attributes=new Dictionary<string,string>{{"material","nylon"},{"size","medium"}},verificationQuestions=Array.Empty<string>()};
 var lostResponse=await Send(HttpMethod.Post,"/api/v1/items",users["lost"].Token,ItemBody(0,"Lost black backpack"));Check(lostResponse.Status==HttpStatusCode.Created,"create Lost Item");var lostItem=GuidProp(lostResponse.Body,"id");items.Add(lostItem);
 var foundResponse=await Send(HttpMethod.Post,"/api/v1/items",users["found"].Token,ItemBody(1,"Found black backpack"));Check(foundResponse.Status==HttpStatusCode.Created,"create Found Item");var foundItem=GuidProp(foundResponse.Body,"id");items.Add(foundItem);
 ItemMatch? match=null;for(var attempt=0;attempt<30&&match is null;attempt++){match=await db.ItemMatches.IgnoreQueryFilters().AsNoTracking().SingleOrDefaultAsync(x=>x.LostItemId==lostItem&&x.FoundItemId==foundItem);if(match is null)await Task.Delay(1000);}Check(match is not null,"durable matching job processed");Check(match!.MatchScore is >=0 and <=100,"deterministic score bounded");Check(!string.IsNullOrWhiteSpace(match.ScoreBreakdownJson)&&!match.ScoreBreakdownJson.Contains("answer",StringComparison.OrdinalIgnoreCase),"safe match explanation");
 var firstRescan=await Send(HttpMethod.Post,$"/api/v1/matches/rescan/{foundItem}",users["found"].Token);var secondRescan=await Send(HttpMethod.Post,$"/api/v1/matches/rescan/{foundItem}",users["found"].Token);Check(firstRescan.Status==HttpStatusCode.Accepted&&secondRescan.Status==HttpStatusCode.Accepted,"duplicate rescans accepted idempotently");Check(await db.ItemMatches.IgnoreQueryFilters().CountAsync(x=>x.LostItemId==lostItem&&x.FoundItemId==foundItem)==1,"one match after rescans");Check(await db.Notifications.CountAsync(x=>x.Type=="match.suggested"&&(x.UserId==users["lost"].Id||x.UserId==users["found"].Id))==2,"one match notification per owner");
 var detail=await Send(HttpMethod.Get,$"/api/v1/matches/{match.Id}",users["lost"].Token);Check(detail.Status==HttpStatusCode.OK,"owner accesses match");var sensitive=new[]{"expectedAnswer","answerCiphertext","codeHash","publicTokenHash","identificationCiphertext","signingKey","connectionString"};Check(sensitive.All(x=>!detail.Body.Contains(x,StringComparison.OrdinalIgnoreCase)),"match DTO excludes private fields");var unrelatedMatch=await Send(HttpMethod.Get,$"/api/v1/matches/{match.Id}",users["unrelated"].Token);Check(unrelatedMatch.Status is HttpStatusCode.NotFound or HttpStatusCode.Forbidden,"unrelated user cannot access match");
 var normalQueue=await Send(HttpMethod.Get,"/api/v1/moderation/reports",users["lost"].Token);Check(normalQueue.Status==HttpStatusCode.Forbidden,"normal moderation access is 403");
 var reportResponse=await Send(HttpMethod.Post,"/api/v1/reports",users["unrelated"].Token,new{itemId=foundItem,reportedUserId=(Guid?)null,messageId=(Guid?)null,reason="spam",details="Disposable Phase 5 verification report"});Check(reportResponse.Status==HttpStatusCode.Created,"create report");var reportId=GuidProp(reportResponse.Body,"id");
 var queue=await Send(HttpMethod.Get,"/api/v1/moderation/reports",users["moderator"].Token);Check(queue.Status==HttpStatusCode.OK&&queue.Body.Contains(reportId.ToString(),StringComparison.OrdinalIgnoreCase),"Moderator accesses report queue");var review=await Send(HttpMethod.Post,$"/api/v1/moderation/reports/{reportId}/transition",users["moderator"].Token,new{status=1,assignToMe=true,internalNotes="Disposable internal note"});Check(review.Status==HttpStatusCode.NoContent,"Moderator starts review");var resolve=await Send(HttpMethod.Post,$"/api/v1/moderation/reports/{reportId}/transition",users["moderator"].Token,new{status=2,assignToMe=true,internalNotes="Disposable internal note"});Check(resolve.Status==HttpStatusCode.NoContent,"Moderator resolves report");Check(!reportResponse.Body.Contains("internalNotes",StringComparison.OrdinalIgnoreCase),"normal report response excludes internal notes");
 var hide=await Send(HttpMethod.Post,$"/api/v1/moderation/items/{foundItem}/hide",users["moderator"].Token,new{reasonCode="verification",internalNotes="temporary",untilUtc=(DateTime?)null});Check(hide.Status==HttpStatusCode.NoContent&&await db.Items.IgnoreQueryFilters().AnyAsync(x=>x.Id==foundItem&&x.IsDeleted&&x.Status==ItemStatus.Removed),"Moderator hides Item");var restore=await Send(HttpMethod.Post,$"/api/v1/moderation/items/{foundItem}/restore",users["moderator"].Token,new{reasonCode="verification_complete",internalNotes="temporary",untilUtc=(DateTime?)null});Check(restore.Status==HttpStatusCode.NoContent&&await db.Items.AnyAsync(x=>x.Id==foundItem&&x.Status==ItemStatus.Active),"Moderator restores Item");
 var refresh=new RefreshToken{UserId=users["found"].Id,TokenHash=$"{run}-refresh",ExpiresAtUtc=DateTime.UtcNow.AddDays(1)};db.RefreshTokens.Add(refresh);await db.SaveChangesAsync();var warn=await Send(HttpMethod.Post,$"/api/v1/moderation/users/{users["found"].Id}/warn",users["moderator"].Token,new{reasonCode="verification_warning",internalNotes="temporary",untilUtc=(DateTime?)null});Check(warn.Status==HttpStatusCode.NoContent,"Moderator warns User");var suspend=await Send(HttpMethod.Post,$"/api/v1/moderation/users/{users["found"].Id}/suspend",users["moderator"].Token,new{reasonCode="verification_suspend",internalNotes="temporary",untilUtc=DateTime.UtcNow.AddMinutes(10)});Check(suspend.Status==HttpStatusCode.NoContent,"Moderator suspends User");await db.Entry(refresh).ReloadAsync();Check(refresh.RevokedAtUtc.HasValue,"suspension revokes refresh tokens");var suspendedAction=await Send(HttpMethod.Post,$"/api/v1/matches/rescan/{foundItem}",users["found"].Token);Check(suspendedAction.Status==HttpStatusCode.Forbidden,"suspended User blocked from protected action");var reactivate=await Send(HttpMethod.Post,$"/api/v1/moderation/users/{users["found"].Id}/reactivate",users["moderator"].Token,new{reasonCode="verification_complete",internalNotes="temporary",untilUtc=(DateTime?)null});Check(reactivate.Status==HttpStatusCode.NoContent,"Moderator reactivates User");
 var permanentByModerator=await Send(HttpMethod.Post,$"/api/v1/moderation/users/{users["lost"].Id}/block",users["moderator"].Token,new{reasonCode="verification",internalNotes="temporary",untilUtc=(DateTime?)null});Check(permanentByModerator.Status==HttpStatusCode.Forbidden,"Moderator denied Admin permanent block");var permanentByAdmin=await Send(HttpMethod.Post,$"/api/v1/moderation/users/{users["lost"].Id}/block",users["admin"].Token,new{reasonCode="verification",internalNotes="temporary",untilUtc=(DateTime?)null});Check(permanentByAdmin.Status==HttpStatusCode.NoContent,"Admin performs permanent block");var adminReactivate=await Send(HttpMethod.Post,$"/api/v1/moderation/users/{users["lost"].Id}/reactivate",users["admin"].Token,new{reasonCode="verification_complete",internalNotes="temporary",untilUtc=(DateTime?)null});Check(adminReactivate.Status==HttpStatusCode.NoContent,"Admin reactivates permanently blocked User");
 var conversationResponse=await Send(HttpMethod.Post,$"/api/v1/conversations?itemId={lostItem}&recipientId={users["unrelated"].Id}",users["lost"].Token);Check(conversationResponse.Status==HttpStatusCode.OK,"create conversation before user block");var conversationId=GuidProp(conversationResponse.Body,"id");conversations.Add(conversationId);var originalMessage=await Send(HttpMethod.Post,$"/api/v1/conversations/{conversationId}/messages",users["lost"].Token,new{body="Disposable message preserved as history"});Check(originalMessage.Status==HttpStatusCode.OK,"send message before user block");var userBlock=await Send(HttpMethod.Post,$"/api/v1/blocks/{users["unrelated"].Id}",users["lost"].Token);Check(userBlock.Status==HttpStatusCode.NoContent,"create user block");var blockedMessage=await Send(HttpMethod.Post,$"/api/v1/conversations/{conversationId}/messages",users["lost"].Token,new{body="This must be blocked"});Check(blockedMessage.Status==HttpStatusCode.Conflict&&await db.Messages.AnyAsync(x=>x.ConversationId==conversationId&&x.Body.Contains("preserved")),"block prevents messages without destroying history");
 var claimResponse=await Send(HttpMethod.Post,$"/api/v1/claims/items/{foundItem}",users["unrelated"].Token,new{answers=Array.Empty<object>()});Check(claimResponse.Status==HttpStatusCode.Created,"create active Claim for block safety");var reciprocalBlock=await Send(HttpMethod.Post,$"/api/v1/blocks/{users["found"].Id}",users["unrelated"].Token);Check(reciprocalBlock.Status==HttpStatusCode.NoContent,"block during active Claim");var requiredConversation=await Send(HttpMethod.Post,$"/api/v1/conversations?itemId={foundItem}&recipientId={users["found"].Id}",users["unrelated"].Token);Check(requiredConversation.Status==HttpStatusCode.OK,"active Claim preserves required return conversation");if(requiredConversation.Status==HttpStatusCode.OK)conversations.Add(GuidProp(requiredConversation.Body,"id"));
 Check(await db.AuditEvents.CountAsync(x=>x.ActorId==users["moderator"].Id||x.ActorId==users["admin"].Id)>=7,"moderation audit records created");var audit=await Send(HttpMethod.Get,"/api/v1/moderation/audit",users["moderator"].Token);Check(audit.Status==HttpStatusCode.OK&&!sensitive.Any(x=>audit.Body.Contains(x,StringComparison.OrdinalIgnoreCase)),"audit DTO is authorized and secret-safe");Check(match.EngineVersion=="deterministic-v1","deterministic fallback remains source of truth");Console.WriteLine("PASS provider boundaries disabled/no-op by configured implementation");
}
finally{
 var ids=users.Values.Select(x=>x.Id).ToArray();if(ids.Length>0){
  var itemIds=await db.Items.IgnoreQueryFilters().Where(x=>ids.Contains(x.OwnerId)).Select(x=>x.Id).ToArrayAsync();var claimIds=await db.Claims.IgnoreQueryFilters().Where(x=>itemIds.Contains(x.ItemId)||ids.Contains(x.ClaimantId)).Select(x=>x.Id).ToArrayAsync();var exchangeIds=await db.Exchanges.IgnoreQueryFilters().Where(x=>claimIds.Contains(x.ClaimId)).Select(x=>x.Id).ToArrayAsync();var conversationIds=await db.ConversationParticipants.Where(x=>ids.Contains(x.UserId)).Select(x=>x.ConversationId).Distinct().ToArrayAsync();
  await db.Ratings.IgnoreQueryFilters().Where(x=>exchangeIds.Contains(x.ExchangeId)||ids.Contains(x.ReviewerId)||ids.Contains(x.RevieweeId)).ExecuteDeleteAsync();await db.ClaimAnswers.IgnoreQueryFilters().Where(x=>claimIds.Contains(x.ClaimId)).ExecuteDeleteAsync();await db.Exchanges.IgnoreQueryFilters().Where(x=>exchangeIds.Contains(x.Id)).ExecuteDeleteAsync();await db.Claims.IgnoreQueryFilters().Where(x=>claimIds.Contains(x.Id)).ExecuteDeleteAsync();await db.Messages.Where(x=>conversationIds.Contains(x.ConversationId)||ids.Contains(x.SenderId)).ExecuteDeleteAsync();await db.ConversationParticipants.Where(x=>conversationIds.Contains(x.ConversationId)||ids.Contains(x.UserId)).ExecuteDeleteAsync();await db.Conversations.Where(x=>conversationIds.Contains(x.Id)).ExecuteDeleteAsync();await db.Reports.Where(x=>ids.Contains(x.ReporterId)||(x.ReportedUserId.HasValue&&ids.Contains(x.ReportedUserId.Value))||(x.ItemId.HasValue&&itemIds.Contains(x.ItemId.Value))).ExecuteDeleteAsync();await db.ItemMatches.IgnoreQueryFilters().Where(x=>itemIds.Contains(x.LostItemId)||itemIds.Contains(x.FoundItemId)).ExecuteDeleteAsync();await db.Notifications.Where(x=>ids.Contains(x.UserId)).ExecuteDeleteAsync();await db.UserBlocks.Where(x=>ids.Contains(x.BlockerId)||ids.Contains(x.BlockedId)).ExecuteDeleteAsync();await db.ModerationRecords.Where(x=>ids.Contains(x.ActorId!.Value)||itemIds.Contains(x.TargetId)||ids.Contains(x.TargetId)).ExecuteDeleteAsync();await db.AuditEvents.Where(x=>(x.ActorId.HasValue&&ids.Contains(x.ActorId.Value))||(x.EntityId.HasValue&&(itemIds.Contains(x.EntityId.Value)||claimIds.Contains(x.EntityId.Value)||exchangeIds.Contains(x.EntityId.Value)))).ExecuteDeleteAsync();await db.Favorites.IgnoreQueryFilters().Where(x=>itemIds.Contains(x.ItemId)||ids.Contains(x.UserId)).ExecuteDeleteAsync();await db.ItemPhotos.IgnoreQueryFilters().Where(x=>itemIds.Contains(x.ItemId)).ExecuteDeleteAsync();await db.ItemAttributes.IgnoreQueryFilters().Where(x=>itemIds.Contains(x.ItemId)).ExecuteDeleteAsync();await db.ClaimQuestions.IgnoreQueryFilters().Where(x=>itemIds.Contains(x.ItemId)).ExecuteDeleteAsync();await db.MatchingJobs.Where(x=>itemIds.Contains(x.ItemId)).ExecuteDeleteAsync();await db.Items.IgnoreQueryFilters().Where(x=>itemIds.Contains(x.Id)).ExecuteDeleteAsync();await db.RefreshTokens.Where(x=>ids.Contains(x.UserId)).ExecuteDeleteAsync();await db.UserRoles.Where(x=>ids.Contains(x.UserId)).ExecuteDeleteAsync();await db.UserClaims.Where(x=>ids.Contains(x.UserId)).ExecuteDeleteAsync();await db.UserLogins.Where(x=>ids.Contains(x.UserId)).ExecuteDeleteAsync();await db.UserTokens.Where(x=>ids.Contains(x.UserId)).ExecuteDeleteAsync();await db.Users.Where(x=>ids.Contains(x.Id)).ExecuteDeleteAsync();
  var remaining=await db.Users.CountAsync(x=>ids.Contains(x.Id))+await db.Items.IgnoreQueryFilters().CountAsync(x=>itemIds.Contains(x.Id))+await db.Claims.IgnoreQueryFilters().CountAsync(x=>claimIds.Contains(x.Id))+await db.Exchanges.IgnoreQueryFilters().CountAsync(x=>exchangeIds.Contains(x.Id))+await db.Conversations.CountAsync(x=>conversationIds.Contains(x.Id))+await db.Notifications.CountAsync(x=>ids.Contains(x.UserId))+await db.UserBlocks.CountAsync(x=>ids.Contains(x.BlockerId)||ids.Contains(x.BlockedId))+await db.ModerationRecords.CountAsync(x=>ids.Contains(x.TargetId)||(x.ActorId.HasValue&&ids.Contains(x.ActorId.Value)))+await db.MatchingJobs.CountAsync(x=>itemIds.Contains(x.ItemId));Check(remaining==0,"disposable data final count is zero");
 }}
