using System.Security.Claims;
using System.Text.Json;
using Asp.Versioning;
using FluentValidation;
using LostFound.Application.Contracts;
using LostFound.Domain.Entities;
using LostFound.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace LostFound.Api.Controllers;
[Authorize,ApiController,ApiVersion(1),Route("api/v{version:apiVersion}/claims")]
public sealed class ClaimsController(LostFoundDbContext db,IDataProtectionProvider protection,IValidator<CreateClaimRequest> createValidator,IValidator<SubmitClaimAnswersRequest> answerValidator):ControllerBase
{
 private Guid UserId=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!); private bool Staff=>User.IsInRole("Moderator")||User.IsInRole("Admin");
 private IDataProtector Protector=>protection.CreateProtector("LostFound.ClaimAnswers.v1");
 [HttpPost("items/{itemId:guid}")] public async Task<ActionResult<ClaimDetailResponse>> Create(Guid itemId,CreateClaimRequest request,CancellationToken ct){var vr=await createValidator.ValidateAsync(request,ct);if(!vr.IsValid)return BadRequest(new ValidationProblemDetails(vr.ToDictionary()));var item=await db.Items.Include(x=>x.ClaimQuestions.Where(q=>q.IsActive)).SingleOrDefaultAsync(x=>x.Id==itemId,ct);if(item is null)return NotFound();if(item.OwnerId==UserId)return BadRequest(Problem("You cannot claim your own listing",400));if(item.Status is not (ItemStatus.Active or ItemStatus.Matched))return Conflict(Problem("Item is not available for claims",409));if(await db.Claims.AnyAsync(x=>x.ItemId==itemId&&x.ClaimantId==UserId&&(x.Status==ClaimStatus.Pending||x.Status==ClaimStatus.UnderReview||x.Status==ClaimStatus.Accepted),ct))return Conflict(Problem("An active claim already exists",409));var answers=request.Answers??[];if(answers.Select(x=>x.QuestionId).Distinct().Count()!=answers.Count||answers.Any(a=>item.ClaimQuestions.All(q=>q.Id!=a.QuestionId)))return BadRequest(Problem("Answers must match this item's questions",400));var claim=new LostFound.Domain.Entities.Claim{ItemId=itemId,ClaimantId=UserId};foreach(var answer in answers){var q=item.ClaimQuestions.Single(x=>x.Id==answer.QuestionId);claim.Answers.Add(new ClaimAnswer{QuestionId=q.Id,QuestionSnapshot=q.Prompt,AnswerCiphertext=Protector.Protect(answer.Answer.Trim())});}db.Claims.Add(claim);Notify(item.OwnerId,"claim.submitted",claim.Id,itemId);await db.SaveChangesAsync(ct);return CreatedAtAction(nameof(Get),new{id=claim.Id,version="1"},await Map(claim.Id,true,ct));}
 [HttpGet("mine")] public Task<ActionResult<PagedResponse<ClaimSummaryResponse>>> Mine(ClaimStatus? status,int page=1,int pageSize=20,CancellationToken ct=default)=>List(db.Claims.Where(x=>x.ClaimantId==UserId),status,page,pageSize,ct);
 [HttpGet("received")] public Task<ActionResult<PagedResponse<ClaimSummaryResponse>>> Received(ClaimStatus? status,int page=1,int pageSize=20,CancellationToken ct=default)=>List(db.Claims.Where(x=>x.Item.OwnerId==UserId),status,page,pageSize,ct);
 [HttpGet("{id:guid}")] public async Task<ActionResult<ClaimDetailResponse>> Get(Guid id,CancellationToken ct){var access=await db.Claims.AnyAsync(x=>x.Id==id&&(x.ClaimantId==UserId||x.Item.OwnerId==UserId),ct);if(!access&&!Staff)return Forbid();return Ok(await Map(id,true,ct));}
 [HttpPut("{id:guid}/answers")] public async Task<ActionResult<ClaimDetailResponse>> Answers(Guid id,SubmitClaimAnswersRequest request,CancellationToken ct){var vr=await answerValidator.ValidateAsync(request,ct);if(!vr.IsValid)return BadRequest(new ValidationProblemDetails(vr.ToDictionary()));var claim=await db.Claims.Include(x=>x.Answers).Include(x=>x.Item).ThenInclude(x=>x.ClaimQuestions).SingleOrDefaultAsync(x=>x.Id==id,ct);if(claim is null)return NotFound();if(claim.ClaimantId!=UserId)return Forbid();if(claim.Status!=ClaimStatus.Pending)return Conflict(Problem("Answers can only be changed while pending",409));var active=claim.Item.ClaimQuestions.Where(x=>x.IsActive).ToDictionary(x=>x.Id);if(request.Answers.Any(x=>!active.ContainsKey(x.QuestionId)))return BadRequest(Problem("Answers must match this item's questions",400));db.ClaimAnswers.RemoveRange(claim.Answers);foreach(var a in request.Answers){var q=active[a.QuestionId];db.ClaimAnswers.Add(new(){ClaimId=id,QuestionId=q.Id,QuestionSnapshot=q.Prompt,AnswerCiphertext=Protector.Protect(a.Answer.Trim())});}await db.SaveChangesAsync(ct);return Ok(await Map(id,true,ct));}
 [HttpPost("{id:guid}/cancel")] public async Task<IActionResult> Cancel(Guid id,CancellationToken ct){var claim=await db.Claims.Include(x=>x.Item).SingleOrDefaultAsync(x=>x.Id==id,ct);if(claim is null)return NotFound();if(claim.ClaimantId!=UserId)return Forbid();if(claim.Status is not (ClaimStatus.Pending or ClaimStatus.UnderReview))return Conflict(Problem("Claim cannot be cancelled",409));claim.Status=ClaimStatus.Cancelled;claim.ConcurrencyToken=Guid.NewGuid();Notify(claim.Item.OwnerId,"claim.cancelled",claim.Id,claim.ItemId);await db.SaveChangesAsync(ct);return NoContent();}
 [HttpPost("{id:guid}/under-review")] public Task<IActionResult> UnderReview(Guid id,CancellationToken ct)=>ReviewState(id,ClaimStatus.UnderReview,ct);
 [HttpPost("{id:guid}/review")] public async Task<IActionResult> Review(Guid id,ReviewClaimRequest request,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var claim=await db.Claims.Include(x=>x.Item).SingleOrDefaultAsync(x=>x.Id==id,ct);if(claim is null)return NotFound();if(claim.Item.OwnerId!=UserId&&!Staff)return Forbid();if(claim.Status is not (ClaimStatus.Pending or ClaimStatus.UnderReview))return Conflict(Problem("Claim is no longer reviewable",409));if(request.Accept&&await db.Claims.AnyAsync(x=>x.ItemId==claim.ItemId&&x.Id!=id&&x.Status==ClaimStatus.Accepted,ct))return Conflict(Problem("This item already has an accepted claim",409));claim.Status=request.Accept?ClaimStatus.Accepted:ClaimStatus.Rejected;claim.ReviewedAtUtc=DateTime.UtcNow;claim.ConcurrencyToken=Guid.NewGuid();if(request.Accept){claim.Item.Status=ItemStatus.Claimed;if(!await db.Exchanges.AnyAsync(x=>x.ClaimId==id,ct))db.Exchanges.Add(new Exchange{ClaimId=id,ItemId=claim.ItemId,OwnerId=claim.Item.OwnerId,ClaimantId=claim.ClaimantId});}Notify(claim.ClaimantId,request.Accept?"claim.accepted":"claim.rejected",claim.Id,claim.ItemId);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return NoContent();}
 private async Task<IActionResult> ReviewState(Guid id,ClaimStatus state,CancellationToken ct){var claim=await db.Claims.Include(x=>x.Item).SingleOrDefaultAsync(x=>x.Id==id,ct);if(claim is null)return NotFound();if(claim.Item.OwnerId!=UserId&&!Staff)return Forbid();if(claim.Status!=ClaimStatus.Pending)return Conflict(Problem("Invalid claim transition",409));claim.Status=state;claim.ReviewedAtUtc=DateTime.UtcNow;Notify(claim.ClaimantId,"claim.underReview",id,claim.ItemId);await db.SaveChangesAsync(ct);return NoContent();}
 private async Task<ActionResult<PagedResponse<ClaimSummaryResponse>>> List(IQueryable<LostFound.Domain.Entities.Claim> q,ClaimStatus? status,int page,int size,CancellationToken ct){page=Math.Max(1,page);size=Math.Clamp(size,1,100);if(status.HasValue)q=q.Where(x=>x.Status==status);var total=await q.CountAsync(ct);var rows=await q.AsNoTracking().OrderByDescending(x=>x.CreatedAtUtc).Skip((page-1)*size).Take(size).Select(x=>new ClaimSummaryResponse(x.Id,x.ItemId,x.Item.Title,x.ClaimantId,x.Status,x.CreatedAtUtc,x.ReviewedAtUtc,x.Exchange==null?null:x.Exchange.Id)).ToListAsync(ct);return Ok(new PagedResponse<ClaimSummaryResponse>(rows,page,size,total));}
 private async Task<ClaimDetailResponse> Map(Guid id,bool includeAnswers,CancellationToken ct){var x=await db.Claims.AsNoTracking().AsSplitQuery().Include(x=>x.Item).ThenInclude(x=>x.ClaimQuestions).Include(x=>x.Answers).Include(x=>x.Exchange).SingleAsync(x=>x.Id==id,ct);var canSee=includeAnswers&&(x.ClaimantId==UserId||x.Item.OwnerId==UserId||Staff);return new(x.Id,x.ItemId,x.Item.Title,x.Item.OwnerId,x.ClaimantId,x.Status,x.CreatedAtUtc,x.ReviewedAtUtc,x.Item.ClaimQuestions.OrderBy(q=>q.SortOrder).Select(q=>new VerificationQuestionResponse(q.Id,q.Prompt,q.SortOrder)).ToList(),canSee?x.Answers.Select(a=>new ClaimAnswerResponse(a.QuestionId,a.QuestionSnapshot,Protector.Unprotect(a.AnswerCiphertext))).ToList():null,x.Exchange?.Id);}
 private void Notify(Guid user,string type,Guid claim,Guid item)=>db.Notifications.Add(new(){UserId=user,Type=type,PayloadJson=JsonSerializer.Serialize(new{claimId=claim,itemId=item})});private static ProblemDetails Problem(string title,int status)=>new(){Title=title,Status=status};
}
