using System.Data;using System.Security.Claims;using System.Text.Json;using Asp.Versioning;using FluentValidation;using LostFound.Application.Contracts;using LostFound.Application.Security;using LostFound.Domain.Entities;using LostFound.Infrastructure.Persistence;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.RateLimiting;using Microsoft.EntityFrameworkCore;
namespace LostFound.Api.Controllers;
[Authorize,ApiController,ApiVersion(1),Route("api/v{version:apiVersion}/exchanges")]
public sealed class ExchangesController(LostFoundDbContext db,IConfiguration config,IValidator<VerifyExchangeCodeRequest> validator):ControllerBase
{
 private Guid UserId=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);private bool Staff=>User.IsInRole("Moderator")||User.IsInRole("Admin");private string Secret=>config["Exchange:HashKey"]??config["Jwt:SigningKey"]!;private int Lifetime=>config.GetValue("Exchange:CodeLifetimeMinutes",10);
 [HttpGet]public async Task<ActionResult> List(CancellationToken ct)=>Ok(await db.Exchanges.AsNoTracking().Where(x=>x.OwnerId==UserId||x.ClaimantId==UserId).OrderByDescending(x=>x.CreatedAtUtc).Select(x=>Map(x,UserId)).ToListAsync(ct));
 [HttpGet("{id:guid}")]public async Task<ActionResult<ExchangeResponse>> Get(Guid id,CancellationToken ct){var x=await db.Exchanges.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();if(x.OwnerId!=UserId&&x.ClaimantId!=UserId&&!Staff)return Forbid();return Ok(Map(x,UserId));}
 [HttpPost("{id:guid}/code"),EnableRateLimiting("ownership")]public async Task<ActionResult<ExchangeCodeResponse>> Code(Guid id,CancellationToken ct){var x=await db.Exchanges.Include(x=>x.Claim).ThenInclude(x=>x.Item).SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();if(x.OwnerId!=UserId)return Forbid();if(x.Status is ExchangeStatus.Completed or ExchangeStatus.Cancelled or ExchangeStatus.Expired)return Conflict(P("Exchange is not active",409));if(x.GenerationCount>=3)return StatusCode(429,P("Code regeneration limit reached",429));var code=OwnershipSecurity.GenerateSixDigitCode();var salt=OwnershipSecurity.GenerateSalt();x.CodeSalt=salt;x.CodeHash=OwnershipSecurity.HashExchangeCode(code,salt,Secret);x.CodeIssuedAtUtc=DateTime.UtcNow;x.ExpiresAtUtc=DateTime.UtcNow.AddMinutes(Lifetime);x.FailedAttempts=0;x.LockedUntilUtc=null;x.GenerationCount++;x.Status=ExchangeStatus.Ready;x.Claim.Item.Status=ItemStatus.ReturnInProgress;x.ConcurrencyToken=Guid.NewGuid();Notify(x.ClaimantId,"exchange.ready",x);Audit("exchange.code_issued",x.Id,new{x.GenerationCount,x.ExpiresAtUtc});await db.SaveChangesAsync(ct);return Ok(new ExchangeCodeResponse(code,x.ExpiresAtUtc.Value));}
 [HttpPost("{id:guid}/verify"),EnableRateLimiting("ownership")]public async Task<ActionResult<ExchangeResponse>> Verify(Guid id,VerifyExchangeCodeRequest r,CancellationToken ct){var vr=await validator.ValidateAsync(r,ct);if(!vr.IsValid)return BadRequest(new ValidationProblemDetails(vr.ToDictionary()));await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var x=await db.Exchanges.Include(x=>x.Claim).ThenInclude(x=>x.Item).SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound();if(x.ClaimantId!=UserId)return Forbid();if(x.Status==ExchangeStatus.Completed){await tx.CommitAsync(ct);return Ok(Map(x,UserId));}if(x.Status!=ExchangeStatus.Ready)return Conflict(P("Exchange is not ready",409));var now=DateTime.UtcNow;if(x.LockedUntilUtc>now)return StatusCode(423,P("Exchange code is temporarily locked",423));if(x.ExpiresAtUtc<=now){x.Status=ExchangeStatus.Expired;Notify(x.OwnerId,"exchange.expired",x);Notify(x.ClaimantId,"exchange.expired",x);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Conflict(P("Exchange code expired",409));}if(!OwnershipSecurity.VerifyExchangeCode(r.Code,x.CodeSalt,Secret,x.CodeHash)){x.FailedAttempts++;if(x.FailedAttempts>=5)x.LockedUntilUtc=now.AddMinutes(15);Audit("exchange.code_failed",x.Id,new{x.FailedAttempts,locked=x.LockedUntilUtc.HasValue});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return BadRequest(P("Invalid exchange code",400));}x.CodeHash="";x.CodeSalt="";x.Status=ExchangeStatus.Completed;x.CompletedAtUtc=now;x.ExpiresAtUtc=null;x.ConcurrencyToken=Guid.NewGuid();x.Claim.Status=ClaimStatus.Completed;x.Claim.CompletedAtUtc=now;x.Claim.ConcurrencyToken=Guid.NewGuid();x.Claim.Item.Status=ItemStatus.Returned;Notify(x.OwnerId,"exchange.completed",x);Notify(x.ClaimantId,"exchange.completed",x);Audit("exchange.completed",x.Id,new{x.ItemId,x.ClaimId});await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Ok(Map(x,UserId));}
 private static ExchangeResponse Map(Exchange x,Guid uid)=>new(x.Id,x.ClaimId,x.ItemId,x.OwnerId,x.ClaimantId,x.Status,x.ExpiresAtUtc,x.FailedAttempts,x.LockedUntilUtc,x.CompletedAtUtc,x.OwnerId==uid&&x.Status is ExchangeStatus.Pending or ExchangeStatus.Ready&&x.GenerationCount<3,x.ClaimantId==uid&&x.Status==ExchangeStatus.Ready,x.Status==ExchangeStatus.Completed);
 private void Notify(Guid user,string type,Exchange x)=>db.Notifications.Add(new(){UserId=user,Type=type,PayloadJson=JsonSerializer.Serialize(new{exchangeId=x.Id,claimId=x.ClaimId,itemId=x.ItemId})});private void Audit(string action,Guid id,object metadata)=>db.AuditEvents.Add(new(){ActorId=UserId,Action=action,EntityType="Exchange",EntityId=id,MetadataJson=JsonSerializer.Serialize(metadata)});private static ProblemDetails P(string title,int status)=>new(){Title=title,Status=status};
}
