using System.Security.Claims;
using Asp.Versioning;
using FluentValidation;
using LostFound.Application.Abstractions;
using LostFound.Application.Contracts;
using LostFound.Domain.Entities;
using LostFound.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LostFound.Api.Controllers;

[ApiController, ApiVersion(1), Route("api/v{version:apiVersion}/items")]
public sealed class ItemsController(LostFoundDbContext db, IFileStorageService storage, IValidator<CreateItemRequest> createValidator, IValidator<UpdateItemRequest> updateValidator, ITextModerationService moderation, IMatchingJobQueue matchingJobs) : ControllerBase
{
    [HttpGet("statistics")]
    public async Task<IActionResult> Statistics(CancellationToken ct) { var items = db.Items.IgnoreQueryFilters().AsNoTracking().Where(x => !x.IsDeleted); return Ok(new { lost = await items.CountAsync(x => x.Type == ItemType.Lost, ct), found = await items.CountAsync(x => x.Type == ItemType.Found, ct), returned = await items.CountAsync(x => x.Status == ItemStatus.Returned, ct) }); }
    [Authorize, HttpGet("mine")]
    public async Task<ActionResult<PagedResponse<ItemResponse>>> Mine([FromQuery] ItemType? type, [FromQuery] ItemStatus? status, [FromQuery] int page = 1, [FromQuery] int pageSize = 20, CancellationToken ct = default) { page = Math.Max(1, page); pageSize = Math.Clamp(pageSize, 1, 50); var query = db.Items.IgnoreQueryFilters().AsNoTracking().Where(x => x.OwnerId == RequireUser() && !x.IsDeleted); if (type.HasValue) query = query.Where(x => x.Type == type); if (status.HasValue) query = query.Where(x => x.Status == status); var total = await query.CountAsync(ct); var rows = await query.AsSplitQuery().Include(x => x.Attributes).Include(x => x.Photos).OrderByDescending(x => x.CreatedAtUtc).Skip((page - 1) * pageSize).Take(pageSize).ToListAsync(ct); return Ok(new PagedResponse<ItemResponse>(rows.Select(x => Map(x, false, true)).ToList(), page, pageSize, total)); }
    [HttpGet]
    public async Task<ActionResult<PagedResponse<ItemResponse>>> Search([FromQuery] string? q, [FromQuery] ItemType? type, [FromQuery] Guid? categoryId, [FromQuery] Guid? subcategoryId, [FromQuery] string? brand, [FromQuery] string? color, [FromQuery] string? location, [FromQuery] double? latitude, [FromQuery] double? longitude, [FromQuery] double? radiusKm, [FromQuery] DateTime? from, [FromQuery] DateTime? to, [FromQuery] bool? hasReward, [FromQuery] string sort = "newest", [FromQuery] int page = 1, [FromQuery] int pageSize = 20, CancellationToken ct = default)
    {
        page = Math.Max(1, page); pageSize = Math.Clamp(pageSize, 1, 50); var query = db.Items.AsNoTracking().Where(x => x.Status == ItemStatus.Active || x.Status == ItemStatus.Matched);
        if (!string.IsNullOrWhiteSpace(q)) { var term = $"%{q.Trim()}%"; query = query.Where(x => EF.Functions.ILike(x.Title, term) || EF.Functions.ILike(x.Description, term)); }
        if (type.HasValue) query = query.Where(x => x.Type == type); if (categoryId.HasValue) query = query.Where(x => x.CategoryId == categoryId); if (subcategoryId.HasValue) query = query.Where(x => x.SubcategoryId == subcategoryId); if (!string.IsNullOrWhiteSpace(brand)) query = query.Where(x => x.Brand == brand); if (!string.IsNullOrWhiteSpace(color)) query = query.Where(x => x.Color == color); if (!string.IsNullOrWhiteSpace(location)) query = query.Where(x => EF.Functions.ILike(x.Location, $"%{location}%")); if (latitude.HasValue && longitude.HasValue && radiusKm is > 0) { var latDelta = radiusKm.Value / 111d; var lonDelta = radiusKm.Value / (111d * Math.Max(.2, Math.Cos(latitude.Value * Math.PI / 180))); query = query.Where(x => x.Latitude >= latitude - latDelta && x.Latitude <= latitude + latDelta && x.Longitude >= longitude - lonDelta && x.Longitude <= longitude + lonDelta); }
        if (from.HasValue) query = query.Where(x => x.OccurredAtUtc >= from); if (to.HasValue) query = query.Where(x => x.OccurredAtUtc <= to); if (hasReward == true) query = query.Where(x => x.RewardAmount > 0);
        query = sort switch { "oldest" => query.OrderBy(x => x.CreatedAtUtc), "title" => query.OrderBy(x => x.Title), _ => query.OrderByDescending(x => x.CreatedAtUtc) }; var total = await query.CountAsync(ct); var entities = await query.AsSplitQuery().Include(x => x.Attributes).Include(x => x.Photos).Skip((page - 1) * pageSize).Take(pageSize).ToListAsync(ct); var uid = CurrentUserId(); return Ok(new PagedResponse<ItemResponse>(entities.Select(x => Map(x, false, x.OwnerId == uid)).ToList(), page, pageSize, total));
    }
    [HttpGet("{id:guid}")]
    public async Task<ActionResult<ItemResponse>> Get(Guid id, CancellationToken ct) { var item = await db.Items.AsSplitQuery().Include(x => x.Photos).Include(x => x.Attributes).FirstOrDefaultAsync(x => x.Id == id, ct); if (item is null) return NotFound(); item.ViewCount++; await db.SaveChangesAsync(ct); var userId = CurrentUserId(); var favorite = userId.HasValue && await db.Favorites.AnyAsync(x => x.UserId == userId && x.ItemId == id, ct); return Ok(Map(item, favorite, item.OwnerId == userId)); }
    [HttpGet("{id:guid}/poster")]
    public async Task<ActionResult<ItemPosterResponse>> Poster(Guid id,CancellationToken ct)
    {
        var ownerId=await db.Items.AsNoTracking().Where(x=>x.Id==id).Select(x=>(Guid?)x.OwnerId).SingleOrDefaultAsync(ct);
        if(ownerId is null)return NotFound();
        var u=await db.Users.AsNoTracking().SingleAsync(x=>x.Id==ownerId,ct);
        var ratings=db.Ratings.Where(x=>x.RevieweeId==ownerId);
        var display=u.AccountType==AccountType.Person?$"{u.FirstName} {u.LastName}".Trim():u.OrganizationName??"User";
        return Ok(new ItemPosterResponse(display,u.ProfilePhotoKey is null?null:$"/uploads/{u.ProfilePhotoKey}",await ratings.AnyAsync(ct)?await ratings.AverageAsync(x=>(decimal)x.Score,ct):null,await ratings.CountAsync(ct),await db.Exchanges.CountAsync(x=>x.CompletedAtUtc!=null&&(x.OwnerId==ownerId||x.ClaimantId==ownerId),ct),u.AllowContactSharing));
    }
    [Authorize, HttpPost]
    public async Task<ActionResult<ItemResponse>> Create(CreateItemRequest request, CancellationToken ct) { var validation = await createValidator.ValidateAsync(request, ct); if (!validation.IsValid) return BadRequest(ToProblem(validation)); var check = await moderation.CheckAsync(string.Join('\n', new[] { request.Title, request.Description }.Concat((request.Attributes ?? []).Select(x => x.Value))), ct); if (!check.IsAllowed) return UnprocessableEntity(new ProblemDetails { Title = "Content cannot be published", Status = 422, Type = "https://httpstatuses.com/422" }); var owner = RequireUser(); if (!await db.Categories.AnyAsync(x => x.Id == request.CategoryId && x.IsActive, ct)) return BadRequest(new ValidationProblemDetails(new Dictionary<string, string[]> { { "categoryId", ["Invalid category."] } })); var item = new Item { OwnerId = owner, Type = request.Type, Title = request.Title.Trim(), Description = request.Description.Trim(), CategoryId = request.CategoryId, SubcategoryId = request.SubcategoryId, Brand = request.Brand, Color = request.Color, Location = request.Location, Latitude = request.Latitude, Longitude = request.Longitude, OccurredAtUtc = request.OccurredAtUtc, RewardAmount = request.RewardAmount }; foreach (var pair in request.Attributes ?? []) item.Attributes.Add(new() { Key = pair.Key, Value = pair.Value }); foreach (var pair in (request.VerificationQuestions ?? []).Select((prompt, index) => (prompt, index))) item.ClaimQuestions.Add(new() { Prompt = pair.prompt.Trim(), ExpectedAnswerHash = "", SortOrder = pair.index }); db.Items.Add(item); await db.SaveChangesAsync(ct); await matchingJobs.EnqueueAsync(item.Id, ct); return CreatedAtAction(nameof(Get), new { id = item.Id, version = "1" }, Map(item, false)); }
    [Authorize, HttpPut("{id:guid}")]
    public async Task<ActionResult<ItemResponse>> Update(Guid id, UpdateItemRequest request, CancellationToken ct) { var validation = await updateValidator.ValidateAsync(request, ct); if (!validation.IsValid) return BadRequest(ToProblem(validation)); var check = await moderation.CheckAsync(string.Join('\n', new[] { request.Title, request.Description }.Concat((request.Attributes ?? []).Select(x => x.Value))), ct); if (!check.IsAllowed) return UnprocessableEntity(new ProblemDetails { Title = "Content cannot be published", Status = 422 }); var owner = RequireUser(); var affected = await db.Items.Where(x => x.Id == id && x.OwnerId == owner && x.Status == ItemStatus.Active).ExecuteUpdateAsync(s => s.SetProperty(x => x.Title, request.Title).SetProperty(x => x.Description, request.Description).SetProperty(x => x.CategoryId, request.CategoryId).SetProperty(x => x.SubcategoryId, request.SubcategoryId).SetProperty(x => x.Brand, request.Brand).SetProperty(x => x.Color, request.Color).SetProperty(x => x.Location, request.Location).SetProperty(x => x.Latitude, request.Latitude).SetProperty(x => x.Longitude, request.Longitude).SetProperty(x => x.OccurredAtUtc, request.OccurredAtUtc).SetProperty(x => x.RewardAmount, request.RewardAmount).SetProperty(x => x.UpdatedAtUtc, DateTime.UtcNow), ct); if (affected == 0) return NotFound(); await db.ItemAttributes.Where(x => x.ItemId == id).ExecuteDeleteAsync(ct); db.ItemAttributes.AddRange((request.Attributes ?? []).Select(x => new ItemAttribute { ItemId = id, Key = x.Key, Value = x.Value })); await db.SaveChangesAsync(ct); await matchingJobs.EnqueueAsync(id, ct); var item = await db.Items.AsNoTracking().Include(x => x.Attributes).Include(x => x.Photos).SingleAsync(x => x.Id == id, ct); return Ok(Map(item, false)); }
    [Authorize, HttpDelete("{id:guid}/photos/{photoId:guid}")]
    public async Task<IActionResult> DeletePhoto(Guid id, Guid photoId, CancellationToken ct) { var photo = await db.ItemPhotos.Include(x => x.Item).SingleOrDefaultAsync(x => x.Id == photoId && x.ItemId == id && x.Item.OwnerId == RequireUser(), ct); if (photo is null) return NotFound(); db.ItemPhotos.Remove(photo); await db.SaveChangesAsync(ct); await storage.DeleteAsync(photo.StorageKey, ct); return NoContent(); }
    [Authorize, HttpDelete("{id:guid}")]
    public async Task<IActionResult> Delete(Guid id, CancellationToken ct) { var item = await db.Items.FirstOrDefaultAsync(x => x.Id == id && x.OwnerId == RequireUser(), ct); if (item is null) return NotFound(); item.IsDeleted = true; item.Status = ItemStatus.Closed; await db.SaveChangesAsync(ct); return NoContent(); }
    [Authorize, HttpPost("{id:guid}/photos"), RequestSizeLimit(10_000_000)]
    public async Task<ActionResult<ItemPhotoResponse>> Upload(Guid id, IFormFile file, CancellationToken ct) { var item = await db.Items.Include(x => x.Photos).FirstOrDefaultAsync(x => x.Id == id && x.OwnerId == RequireUser(), ct); if (item is null) return NotFound(); if (item.Photos.Count >= 8) return Conflict(new ProblemDetails { Title = "Maximum of 8 photos reached", Status = 409 }); if (file.Length <= 0 || file.Length > 8_000_000) return BadRequest(new ValidationProblemDetails(new Dictionary<string, string[]> { { "file", ["Image must be between 1 byte and 8 MB."] } })); await using var stream = file.OpenReadStream(); var key = await storage.SaveImageAsync(stream, file.ContentType, ct); var photo = new ItemPhoto { ItemId = id, StorageKey = key, ContentType = file.ContentType, SizeBytes = file.Length, SortOrder = item.Photos.Count }; db.ItemPhotos.Add(photo); await db.SaveChangesAsync(ct); return Ok(new ItemPhotoResponse(photo.Id, $"/uploads/{key}", photo.SortOrder)); }
    private Guid? CurrentUserId() => Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out var id) ? id : null; private Guid RequireUser() => CurrentUserId() ?? throw new UnauthorizedAccessException();
    private static ValidationProblemDetails ToProblem(FluentValidation.Results.ValidationResult result) => new(result.Errors.GroupBy(x => char.ToLowerInvariant(x.PropertyName[0]) + x.PropertyName[1..]).ToDictionary(x => x.Key, x => x.Select(e => e.ErrorMessage).ToArray()));
    private static ItemResponse Map(Item x, bool fav, bool canManage = false) => new(x.Id, canManage, x.Type, x.Status, x.Title, x.Description, x.CategoryId, x.SubcategoryId, x.Brand, x.Color, x.Location, x.Latitude, x.Longitude, x.OccurredAtUtc, x.RewardAmount, x.ViewCount, x.CreatedAtUtc, x.Attributes.ToDictionary(a => a.Key, a => a.Value), x.Photos.OrderBy(p => p.SortOrder).Select(p => new ItemPhotoResponse(p.Id, $"/uploads/{p.StorageKey}", p.SortOrder)).ToList(), fav);
}
