using System.Security.Claims;
using System.Text.Json;
using Asp.Versioning;
using LostFound.Domain.Entities;
using LostFound.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LostFound.Api.Controllers;
[Authorize(Policy="Moderator"),ApiController,ApiVersion(1),Route("api/v{version:apiVersion}/moderation")]
public sealed class ModerationController(LostFoundDbContext db):ControllerBase {
 Guid UserId=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
 [HttpGet("reports")]public async Task<ActionResult> Reports(ReportStatus? status,string? reason,string? severity,DateTime? from,DateTime? to,int page=1,int pageSize=25,CancellationToken ct=default){page=Math.Max(page,1);pageSize=Math.Clamp(pageSize,1,100);var q=db.Reports.AsNoTracking();if(status.HasValue)q=q.Where(x=>x.Status==status);if(!string.IsNullOrWhiteSpace(reason))q=q.Where(x=>x.Reason==reason);if(!string.IsNullOrWhiteSpace(severity))q=q.Where(x=>x.Severity==severity);if(from.HasValue)q=q.Where(x=>x.CreatedAtUtc>=from);if(to.HasValue)q=q.Where(x=>x.CreatedAtUtc<=to);var total=await q.CountAsync(ct);var rows=await q.OrderByDescending(x=>x.CreatedAtUtc).Skip((page-1)*pageSize).Take(pageSize).Select(x=>new{x.Id,x.ItemId,x.ReportedUserId,x.MessageId,x.Reason,x.Details,x.Severity,x.Status,x.AssignedModeratorId,x.InternalNotes,x.CreatedAtUtc}).ToListAsync(ct);return Ok(new{items=rows,page,pageSize,total});}
 [HttpPost("reports/{id:guid}/transition")]public async Task<IActionResult> Transition(Guid id,ReportTransition request,CancellationToken ct){var report=await db.Reports.SingleOrDefaultAsync(x=>x.Id==id,ct);if(report is null)return NotFound();var allowed=report.Status switch{ReportStatus.Open=>new[]{ReportStatus.UnderReview,ReportStatus.Dismissed,ReportStatus.Escalated},ReportStatus.UnderReview=>new[]{ReportStatus.Resolved,ReportStatus.Dismissed,ReportStatus.Escalated},ReportStatus.Escalated=>new[]{ReportStatus.UnderReview,ReportStatus.Resolved},_=>[]};if(!allowed.Contains(request.Status))return Conflict(new ProblemDetails{Title="Invalid report transition",Status=409});var previous=report.Status;report.Status=request.Status;report.AssignedModeratorId=request.AssignToMe?UserId:report.AssignedModeratorId;if(request.InternalNotes is not null)report.InternalNotes=request.InternalNotes.Trim();report.ConcurrencyToken=Guid.NewGuid();Audit("report.status",report.Id,new{previous,current=report.Status});await db.SaveChangesAsync(ct);return NoContent();}
 [HttpPost("items/{id:guid}/{operation}")]public async Task<IActionResult> Item(Guid id,string operation,ModerationAction request,CancellationToken ct){var item=await db.Items.IgnoreQueryFilters().SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null)return NotFound();if(operation=="hide"){item.Status=ItemStatus.Removed;item.IsDeleted=true;}else if(operation=="restore"){item.Status=ItemStatus.Active;item.IsDeleted=false;}else return BadRequest();Record("Item",id,operation,request);await db.SaveChangesAsync(ct);return NoContent();}
 [HttpPost("users/{id:guid}/{operation}")]public async Task<IActionResult> UserAction(Guid id,string operation,ModerationAction request,CancellationToken ct){if(id==UserId)return BadRequest(new ProblemDetails{Title="Self-moderation is not allowed",Status=400});var user=await db.Users.SingleOrDefaultAsync(x=>x.Id==id,ct);if(user is null)return NotFound();switch(operation){case "suspend":user.IsSuspended=true;user.SuspendedUntilUtc=request.UntilUtc;break;case "reactivate" when user.IsPermanentlyBlocked&&!User.IsInRole("Admin"):return Forbid();case "reactivate":user.IsSuspended=false;user.SuspendedUntilUtc=null;user.IsPermanentlyBlocked=false;break;case "block" when User.IsInRole("Admin"):user.IsPermanentlyBlocked=true;user.IsSuspended=true;break;case "block":return Forbid();case "warn":break;default:return BadRequest();}user.RestrictionReasonCode=request.ReasonCode; if(operation is "suspend" or "block")await db.RefreshTokens.Where(x=>x.UserId==id&&x.RevokedAtUtc==null).ExecuteUpdateAsync(s=>s.SetProperty(x=>x.RevokedAtUtc,DateTime.UtcNow),ct);Record("User",id,operation,request);await db.SaveChangesAsync(ct);return NoContent();}
 [HttpGet("audit")]public async Task<ActionResult> Audit(string? targetType,Guid? targetId,int page=1,int pageSize=50,CancellationToken ct=default){var q=db.AuditEvents.AsNoTracking();if(targetType is not null)q=q.Where(x=>x.EntityType==targetType);if(targetId.HasValue)q=q.Where(x=>x.EntityId==targetId);return Ok(await q.OrderByDescending(x=>x.CreatedAtUtc).Skip((Math.Max(1,page)-1)*Math.Clamp(pageSize,1,100)).Take(Math.Clamp(pageSize,1,100)).Select(x=>new{x.Id,x.ActorId,x.Action,x.EntityType,x.EntityId,x.MetadataJson,x.CreatedAtUtc}).ToListAsync(ct));}
 void Record(string type,Guid id,string action,ModerationAction r){db.ModerationRecords.Add(new(){TargetType=type,TargetId=id,Outcome=action=="restore"?ModerationOutcome.Allowed:ModerationOutcome.ReviewRequired,ReasonCode=r.ReasonCode,ActorId=UserId,InternalNotes=r.InternalNotes,CorrelationId=HttpContext.TraceIdentifier});Audit($"moderation.{action}",id,new{type,r.ReasonCode});}
 void Audit(string action,Guid id,object metadata)=>db.AuditEvents.Add(new(){ActorId=UserId,Action=action,EntityType="Moderation",EntityId=id,MetadataJson=JsonSerializer.Serialize(metadata)});
 public sealed record ReportTransition(ReportStatus Status,bool AssignToMe,string? InternalNotes);public sealed record ModerationAction(string ReasonCode,string? InternalNotes,DateTime? UntilUtc);
}
