using System.Security.Claims; using Asp.Versioning; using FluentValidation; using LostFound.Application.Abstractions; using LostFound.Application.Contracts; using LostFound.Infrastructure.Identity; using LostFound.Infrastructure.Persistence; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Identity; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.RateLimiting;
using LostFound.Domain.Entities;
namespace LostFound.Api.Controllers;
[ApiController,ApiVersion(1),Route("api/v{version:apiVersion}/profiles")]
public sealed class ProfilesController(LostFoundDbContext db,UserManager<ApplicationUser> users,IFileStorageService storage,IValidator<UpdateProfileRequest> validator,IValidator<ChangePasswordRequest> passwordValidator):ControllerBase{
 private Guid UserId=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!); private static string Name(ApplicationUser u)=>u.AccountType==AccountType.Person?$"{u.FirstName} {u.LastName}".Trim():u.OrganizationName??"User";
 [HttpGet("{id:guid}")] public async Task<ActionResult<PublicProfileResponse>> Public(Guid id,CancellationToken ct){var u=await db.Users.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct);if(u is null)return NotFound();var ratings=db.Ratings.Where(x=>x.RevieweeId==id);return Ok(new PublicProfileResponse(id,Name(u),u.ProfilePhotoKey is null?null:$"/uploads/{u.ProfilePhotoKey}",await ratings.AnyAsync(ct)?await ratings.AverageAsync(x=>(decimal)x.Score,ct):null,await ratings.CountAsync(ct),await db.Exchanges.CountAsync(x=>x.CompletedAtUtc!=null&&x.Claim.ClaimantId==id,ct)));}
 [Authorize,HttpGet("me")] public async Task<ActionResult<PrivateProfileResponse>> Me()=>Ok(Map((await users.FindByIdAsync(UserId.ToString()))!));
 [Authorize,HttpPut("me")] public async Task<ActionResult<PrivateProfileResponse>> Update(UpdateProfileRequest r,CancellationToken ct){var vr=await validator.ValidateAsync(r,ct);if(!vr.IsValid)return BadRequest(new ValidationProblemDetails(vr.ToDictionary()));var u=(await users.FindByIdAsync(UserId.ToString()))!;if(u.AccountType==AccountType.Person&&(string.IsNullOrWhiteSpace(r.FirstName)||string.IsNullOrWhiteSpace(r.LastName))||u.AccountType==AccountType.Organization&&string.IsNullOrWhiteSpace(r.OrganizationName))return BadRequest(new ProblemDetails{Title="Required profile fields are missing",Status=400});u.FirstName=r.FirstName;u.LastName=r.LastName;u.OrganizationName=r.OrganizationName;u.ResponsiblePerson=r.ResponsiblePerson;u.PhoneNumber=r.PhoneNumber;u.Language=r.Language;u.Theme=r.Theme;u.NotificationsEnabled=r.NotificationsEnabled;u.EmailNotificationsEnabled=r.EmailNotificationsEnabled;u.InAppNotificationsEnabled=r.InAppNotificationsEnabled;u.AllowContactSharing=r.AllowContactSharing;await users.UpdateAsync(u);return Ok(Map(u));}
 [Authorize,HttpPost("me/photo"),RequestSizeLimit(6_000_000)] public async Task<ActionResult> Photo(IFormFile file,CancellationToken ct){if(file.Length is <=0 or >5_000_000)return BadRequest();var u=(await users.FindByIdAsync(UserId.ToString()))!;await using var stream=file.OpenReadStream();var key=await storage.SaveImageAsync(stream,file.ContentType,ct);if(u.ProfilePhotoKey is not null)await storage.DeleteAsync(u.ProfilePhotoKey,ct);u.ProfilePhotoKey=key;await users.UpdateAsync(u);return Ok(new{url=$"/uploads/{key}"});}
 [Authorize,HttpDelete("me/photo")] public async Task<IActionResult> RemovePhoto(CancellationToken ct){var u=(await users.FindByIdAsync(UserId.ToString()))!;if(u.ProfilePhotoKey is not null)await storage.DeleteAsync(u.ProfilePhotoKey,ct);u.ProfilePhotoKey=null;await users.UpdateAsync(u);return NoContent();}
 [Authorize,HttpPost("me/password"),EnableRateLimiting("auth")] public async Task<IActionResult> Password(ChangePasswordRequest r,CancellationToken ct){var vr=await passwordValidator.ValidateAsync(r,ct);if(!vr.IsValid)return BadRequest(new ValidationProblemDetails(vr.ToDictionary()));var u=(await users.FindByIdAsync(UserId.ToString()))!;var result=await users.ChangePasswordAsync(u,r.CurrentPassword,r.NewPassword);if(!result.Succeeded)return BadRequest(new ProblemDetails{Title="Password change failed",Status=400});await users.UpdateSecurityStampAsync(u);return NoContent();}
 private static PrivateProfileResponse Map(ApplicationUser u)=>new(u.Id,u.AccountType,u.FirstName,u.LastName,u.OrganizationName,u.ResponsiblePerson,u.Email!,u.PhoneNumber,u.ProfilePhotoKey is null?null:$"/uploads/{u.ProfilePhotoKey}",u.Language,u.Theme,u.NotificationsEnabled,u.EmailNotificationsEnabled,u.InAppNotificationsEnabled,u.AllowContactSharing);
}
