using System.Security.Claims;using System.Text.Json;using Asp.Versioning;using FluentValidation;using LostFound.Application.Abstractions;using LostFound.Application.Contracts;using LostFound.Application.Security;using LostFound.Domain.Entities;using LostFound.Infrastructure.Persistence;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.RateLimiting;using Microsoft.EntityFrameworkCore;
namespace LostFound.Api.Controllers;
[ApiController,ApiVersion(1),Route("api/v{version:apiVersion}")]
public sealed class QrTagsController(LostFoundDbContext db,IConfiguration config,IQrCodeRenderer renderer,IValidator<CreateQrTagRequest> createValidator,IValidator<QrContactRequest> contactValidator):ControllerBase
{
 private Guid UserId=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
 [Authorize,HttpPost("qr-tags")]public async Task<ActionResult<QrTokenResponse>> Create(CreateQrTagRequest r,CancellationToken ct){var vr=await createValidator.ValidateAsync(r,ct);if(!vr.IsValid)return BadRequest(new ValidationProblemDetails(vr.ToDictionary()));if(r.ItemId.HasValue&&!await db.Items.AnyAsync(x=>x.Id==r.ItemId&&x.OwnerId==UserId,ct))return BadRequest(new ProblemDetails{Title="Invalid item",Status=400});var token=OwnershipSecurity.GenerateToken();var tag=new QrToken{OwnerId=UserId,ItemId=r.ItemId,Label=r.Label.Trim(),Description=r.Description?.Trim(),PublicTokenHash=OwnershipSecurity.HashQrToken(token)};db.Add(tag);await db.SaveChangesAsync(ct);return Created($"/api/v1/qr-tags/{tag.Id}",new QrTokenResponse(tag.Id,token,PublicUrl(token)));}
 [Authorize,HttpGet("qr-tags")]public async Task<ActionResult> List(CancellationToken ct)=>Ok(await db.QrTokens.AsNoTracking().Where(x=>x.OwnerId==UserId).OrderByDescending(x=>x.CreatedAtUtc).Select(x=>new QrTagResponse(x.Id,x.Label,x.Description,x.ItemId,x.IsActive,x.RevokedAtUtc!=null,x.CreatedAtUtc,x.Scans.Count)).ToListAsync(ct));
 [Authorize,HttpGet("qr-tags/{id:guid}")]public async Task<ActionResult> Get(Guid id,CancellationToken ct){var x=await db.QrTokens.AsNoTracking().Where(x=>x.Id==id&&x.OwnerId==UserId).Select(x=>new QrTagResponse(x.Id,x.Label,x.Description,x.ItemId,x.IsActive,x.RevokedAtUtc!=null,x.CreatedAtUtc,x.Scans.Count)).SingleOrDefaultAsync(ct);return x is null?NotFound():Ok(x);}
 [Authorize,HttpPut("qr-tags/{id:guid}/state")]public async Task<IActionResult> State(Guid id,UpdateQrStateRequest r,CancellationToken ct){var x=await db.QrTokens.SingleOrDefaultAsync(x=>x.Id==id&&x.OwnerId==UserId,ct);if(x is null)return NotFound();if(x.RevokedAtUtc!=null)return Conflict();x.IsActive=r.IsActive;await db.SaveChangesAsync(ct);return NoContent();}
 [Authorize,HttpPost("qr-tags/{id:guid}/rotate")]public async Task<ActionResult<QrTokenResponse>> Rotate(Guid id,CancellationToken ct){var x=await db.QrTokens.SingleOrDefaultAsync(x=>x.Id==id&&x.OwnerId==UserId,ct);if(x is null)return NotFound();var token=OwnershipSecurity.GenerateToken();x.PublicTokenHash=OwnershipSecurity.HashQrToken(token);x.RevokedAtUtc=null;x.IsActive=true;x.UpdatedAtUtc=DateTime.UtcNow;await db.SaveChangesAsync(ct);return Ok(new QrTokenResponse(x.Id,token,PublicUrl(token)));}
 [Authorize,HttpPost("qr-tags/{id:guid}/render")]public async Task<IActionResult> Render(Guid id,[FromQuery]string format,RenderQrRequest request,CancellationToken ct){var x=await db.QrTokens.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.OwnerId==UserId,ct);if(x is null)return NotFound();if(!x.IsActive||x.RevokedAtUtc!=null)return Conflict(new ProblemDetails{Title="QR tag is unavailable",Status=409});if(!OwnershipSecurity.VerifyQrToken(request.Token,x.PublicTokenHash))return BadRequest(new ProblemDetails{Title="QR token does not match this tag",Status=400});var parsed=format.Equals("png",StringComparison.OrdinalIgnoreCase)?QrImageFormat.Png:format.Equals("svg",StringComparison.OrdinalIgnoreCase)?QrImageFormat.Svg:(QrImageFormat?)null;if(parsed is null)return BadRequest(new ProblemDetails{Title="Format must be svg or png",Status=400});var image=renderer.Render(PublicUrl(request.Token),parsed.Value);return File(image.Content,image.ContentType,$"foundly-{id:N}.{image.FileExtension}");}
 [Authorize,HttpPost("qr-tags/{id:guid}/revoke")]public async Task<IActionResult> Revoke(Guid id,CancellationToken ct){var x=await db.QrTokens.SingleOrDefaultAsync(x=>x.Id==id&&x.OwnerId==UserId,ct);if(x is null)return NotFound();x.RevokedAtUtc??=DateTime.UtcNow;x.IsActive=false;await db.SaveChangesAsync(ct);return NoContent();}
 [Authorize,HttpGet("qr-tags/{id:guid}/scans")]public async Task<ActionResult> Scans(Guid id,CancellationToken ct){if(!await db.QrTokens.AnyAsync(x=>x.Id==id&&x.OwnerId==UserId,ct))return NotFound();return Ok(await db.QrScans.AsNoTracking().Where(x=>x.QrTokenId==id).OrderByDescending(x=>x.CreatedAtUtc).Take(200).Select(x=>new QrScanResponse(x.Id,x.CreatedAtUtc,x.CoarseLocation,x.ContactRequested)).ToListAsync(ct));}
 [AllowAnonymous,HttpGet("qr/{token}"),EnableRateLimiting("publicQr")]public async Task<ActionResult<PublicQrResponse>> Scan(string token,CancellationToken ct){var hash=OwnershipSecurity.HashQrToken(token);var x=await db.QrTokens.Include(x=>x.Scans).SingleOrDefaultAsync(x=>x.PublicTokenHash==hash&&x.IsActive&&x.RevokedAtUtc==null,ct);if(x is null)return NotFound(new ProblemDetails{Title="QR tag is unavailable",Status=404});db.QrScans.Add(new(){QrTokenId=x.Id});await db.SaveChangesAsync(ct);var sharing=await db.Users.Where(u=>u.Id==x.OwnerId).Select(u=>u.AllowContactSharing).SingleAsync(ct);return Ok(new PublicQrResponse(x.Label,x.Description,sharing));}
 [AllowAnonymous,HttpPost("qr/{token}/contact"),EnableRateLimiting("publicQr")]public async Task<IActionResult> Contact(string token,QrContactRequest r,CancellationToken ct){var vr=await contactValidator.ValidateAsync(r,ct);if(!vr.IsValid)return BadRequest(new ValidationProblemDetails(vr.ToDictionary()));var hash=OwnershipSecurity.HashQrToken(token);var x=await db.QrTokens.SingleOrDefaultAsync(x=>x.PublicTokenHash==hash&&x.IsActive&&x.RevokedAtUtc==null,ct);if(x is null)return NotFound(new ProblemDetails{Title="QR tag is unavailable",Status=404});db.QrScans.Add(new(){QrTokenId=x.Id,CoarseLocation=r.CoarseLocation?.Trim(),ContactRequested=true});db.Notifications.Add(new(){UserId=x.OwnerId,Type="qr.contactRequested",PayloadJson=JsonSerializer.Serialize(new{qrTagId=x.Id,message=r.Message.Trim()})});await db.SaveChangesAsync(ct);return Accepted();}
 private string PublicUrl(string token)=>$"{config["PublicWebBaseUrl"]?.TrimEnd('/')??""}/qr/{token}";
}
