using System.Linq.Expressions;
using LostFound.Domain.Entities;
using LostFound.Infrastructure.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace LostFound.Infrastructure.Persistence;

public sealed class LostFoundDbContext(DbContextOptions<LostFoundDbContext> options) : IdentityDbContext<ApplicationUser, IdentityRole<Guid>, Guid>(options)
{
 public DbSet<Category> Categories => Set<Category>(); public DbSet<Subcategory> Subcategories => Set<Subcategory>(); public DbSet<Item> Items => Set<Item>(); public DbSet<ItemPhoto> ItemPhotos => Set<ItemPhoto>(); public DbSet<ItemAttribute> ItemAttributes => Set<ItemAttribute>(); public DbSet<Favorite> Favorites => Set<Favorite>(); public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>(); public DbSet<Claim> Claims => Set<Claim>(); public DbSet<ClaimQuestion> ClaimQuestions => Set<ClaimQuestion>(); public DbSet<ClaimAnswer> ClaimAnswers => Set<ClaimAnswer>(); public DbSet<ItemMatch> ItemMatches => Set<ItemMatch>(); public DbSet<Conversation> Conversations => Set<Conversation>(); public DbSet<ConversationParticipant> ConversationParticipants => Set<ConversationParticipant>(); public DbSet<Message> Messages => Set<Message>(); public DbSet<Exchange> Exchanges => Set<Exchange>(); public DbSet<Rating> Ratings => Set<Rating>(); public DbSet<Report> Reports => Set<Report>(); public DbSet<Notification> Notifications => Set<Notification>(); public DbSet<QrToken> QrTokens => Set<QrToken>(); public DbSet<QrScan> QrScans => Set<QrScan>(); public DbSet<AuditEvent> AuditEvents => Set<AuditEvent>(); public DbSet<UserBlock> UserBlocks => Set<UserBlock>(); public DbSet<ModerationRecord> ModerationRecords => Set<ModerationRecord>(); public DbSet<MatchingJob> MatchingJobs => Set<MatchingJob>();
 protected override void OnModelCreating(ModelBuilder b) {
  base.OnModelCreating(b);
  b.Entity<Category>().HasIndex(x => x.Slug).IsUnique(); b.Entity<Subcategory>().HasIndex(x => new { x.CategoryId, x.Slug }).IsUnique();
  b.Entity<Item>().HasQueryFilter(x => !x.IsDeleted); b.Entity<Item>().HasIndex(x => new { x.Type, x.Status, x.CreatedAtUtc }); b.Entity<Item>().HasIndex(x => x.CategoryId); b.Entity<Item>().HasIndex(x => x.SubcategoryId); b.Entity<Item>().HasIndex(x => x.OwnerId); b.Entity<Item>().HasIndex(x => x.OccurredAtUtc); b.Entity<Item>().HasIndex(x => x.Brand); b.Entity<Item>().HasIndex(x => x.Color); b.Entity<Item>().HasIndex(x => new{x.Latitude,x.Longitude}); b.Entity<Item>().HasOne(x => x.Category).WithMany(x => x.Items).OnDelete(DeleteBehavior.Restrict); b.Entity<Item>().HasOne(x => x.Subcategory).WithMany(x => x.Items).OnDelete(DeleteBehavior.Restrict);
  // Required dependents intentionally share Item's visibility filter. Historical/moderation
  // workflows use IgnoreQueryFilters explicitly; public/default queries cannot leak removed Items.
  b.Entity<ItemPhoto>().HasQueryFilter(x=>!x.Item.IsDeleted); b.Entity<ItemAttribute>().HasQueryFilter(x=>!x.Item.IsDeleted); b.Entity<Favorite>().HasQueryFilter(x=>!x.Item.IsDeleted);
  b.Entity<ItemPhoto>().HasIndex(x => new { x.ItemId, x.SortOrder }).IsUnique(); b.Entity<ItemAttribute>().HasIndex(x => new { x.ItemId, x.Key }).IsUnique(); b.Entity<Favorite>().HasIndex(x => new { x.UserId, x.ItemId }).IsUnique(); b.Entity<Favorite>().HasOne(x => x.Item).WithMany().OnDelete(DeleteBehavior.Restrict); b.Entity<RefreshToken>().HasIndex(x => x.TokenHash).IsUnique();
  b.Entity<Claim>().HasQueryFilter(x=>!x.Item.IsDeleted); b.Entity<ClaimQuestion>().HasQueryFilter(x=>!x.Item.IsDeleted); b.Entity<ClaimAnswer>().HasQueryFilter(x=>!x.Claim.Item.IsDeleted&&!x.Question.Item.IsDeleted); b.Entity<Exchange>().HasQueryFilter(x=>!x.Item.IsDeleted); b.Entity<Rating>().HasQueryFilter(x=>!x.Exchange.Item.IsDeleted);
  b.Entity<Claim>().HasOne(x => x.Item).WithMany(x => x.Claims).OnDelete(DeleteBehavior.Restrict); b.Entity<Claim>().HasIndex(x=>new{x.ItemId,x.ClaimantId,x.Status}); b.Entity<Claim>().Property(x=>x.ConcurrencyToken).IsConcurrencyToken(); b.Entity<ClaimQuestion>().HasOne(x => x.Item).WithMany(x => x.ClaimQuestions).OnDelete(DeleteBehavior.Restrict); b.Entity<ClaimQuestion>().HasIndex(x=>new{x.ItemId,x.SortOrder}).IsUnique(); b.Entity<ClaimAnswer>().HasIndex(x => new { x.ClaimId, x.QuestionId }).IsUnique(); b.Entity<ClaimAnswer>().HasOne(x=>x.Claim).WithMany(x=>x.Answers).OnDelete(DeleteBehavior.Restrict); b.Entity<ClaimAnswer>().HasOne(x=>x.Question).WithMany().OnDelete(DeleteBehavior.Restrict);
  b.Entity<ItemMatch>().HasQueryFilter(x=>!x.LostItem.IsDeleted&&!x.FoundItem.IsDeleted); b.Entity<ItemMatch>().HasIndex(x => new { x.LostItemId, x.FoundItemId }).IsUnique(); b.Entity<ItemMatch>().HasIndex(x=>new{x.Status,x.MatchScore,x.UpdatedAtUtc}); b.Entity<ItemMatch>().HasOne(x => x.LostItem).WithMany().OnDelete(DeleteBehavior.Restrict); b.Entity<ItemMatch>().HasOne(x => x.FoundItem).WithMany().OnDelete(DeleteBehavior.Restrict); b.Entity<ItemMatch>().Property(x=>x.ConcurrencyToken).IsConcurrencyToken();
  b.Entity<Conversation>().HasIndex(x=>x.DirectKey).IsUnique(); b.Entity<ConversationParticipant>().HasIndex(x => new { x.ConversationId, x.UserId }).IsUnique(); b.Entity<Message>().HasIndex(x=>new{x.ConversationId,x.CreatedAtUtc}); b.Entity<Message>().HasOne(x => x.Conversation).WithMany(x => x.Messages).OnDelete(DeleteBehavior.Restrict); b.Entity<Exchange>().HasIndex(x => x.ClaimId).IsUnique(); b.Entity<Exchange>().HasIndex(x=>new{x.ItemId,x.Status}); b.Entity<Exchange>().HasOne(x => x.Claim).WithOne(x=>x.Exchange).HasForeignKey<Exchange>(x=>x.ClaimId).OnDelete(DeleteBehavior.Restrict); b.Entity<Exchange>().HasOne(x=>x.Item).WithMany().OnDelete(DeleteBehavior.Restrict); b.Entity<Exchange>().Property(x=>x.ConcurrencyToken).IsConcurrencyToken();
  b.Entity<Rating>().HasIndex(x => new { x.ExchangeId, x.ReviewerId, x.RevieweeId }).IsUnique(); b.Entity<Rating>().ToTable(t => t.HasCheckConstraint("CK_Ratings_Score", "\"Score\" BETWEEN 1 AND 5")); b.Entity<Report>().HasIndex(x => new { x.Status, x.Severity, x.CreatedAtUtc }); b.Entity<Report>().HasIndex(x=>x.AssignedModeratorId); b.Entity<Report>().Property(x=>x.ConcurrencyToken).IsConcurrencyToken(); b.Entity<Report>().HasOne(x => x.Item).WithMany().OnDelete(DeleteBehavior.Restrict); b.Entity<Report>().HasOne(x => x.Message).WithMany().OnDelete(DeleteBehavior.Restrict);
  b.Entity<Notification>().HasIndex(x => new { x.UserId, x.ReadAtUtc, x.CreatedAtUtc }); b.Entity<QrToken>().HasIndex(x => x.PublicTokenHash).IsUnique(); b.Entity<QrToken>().HasIndex(x=>new{x.OwnerId,x.IsActive}); b.Entity<QrToken>().HasOne(x => x.Item).WithMany().OnDelete(DeleteBehavior.Restrict); b.Entity<QrScan>().HasIndex(x=>new{x.QrTokenId,x.CreatedAtUtc}); b.Entity<QrScan>().HasOne(x=>x.QrToken).WithMany(x=>x.Scans).OnDelete(DeleteBehavior.Restrict); b.Entity<AuditEvent>().HasIndex(x => new { x.EntityType, x.EntityId, x.CreatedAtUtc }); b.Entity<Item>().Property(x => x.RewardAmount).HasPrecision(12,2); b.Entity<ItemMatch>().Property(x => x.MatchScore).HasPrecision(5,2);
  b.Entity<UserBlock>().HasIndex(x=>new{x.BlockerId,x.BlockedId}).IsUnique(); b.Entity<UserBlock>().ToTable(t=>t.HasCheckConstraint("CK_UserBlocks_DifferentUsers","\"BlockerId\" <> \"BlockedId\"")); b.Entity<ModerationRecord>().HasIndex(x=>new{x.TargetType,x.TargetId,x.CreatedAtUtc}); b.Entity<ModerationRecord>().HasIndex(x=>new{x.Outcome,x.CreatedAtUtc});
  b.Entity<MatchingJob>().HasIndex(x=>x.ItemId).IsUnique(); b.Entity<MatchingJob>().HasIndex(x=>new{x.Status,x.NextAttemptAtUtc,x.LockedAtUtc}); b.Entity<MatchingJob>().Property(x=>x.ConcurrencyToken).IsConcurrencyToken(); b.Entity<MatchingJob>().HasOne<Item>().WithMany().HasForeignKey(x=>x.ItemId).OnDelete(DeleteBehavior.Restrict);
  LinkUser<Item>(b, x => x.OwnerId); LinkUser<Favorite>(b, x => x.UserId); LinkUser<RefreshToken>(b, x => x.UserId); LinkUser<Claim>(b, x => x.ClaimantId); LinkUser<ConversationParticipant>(b, x => x.UserId); LinkUser<Message>(b, x => x.SenderId); LinkUser<Exchange>(b,x=>x.OwnerId); LinkUser<Exchange>(b,x=>x.ClaimantId); LinkUser<Rating>(b, x => x.ReviewerId); LinkUser<Rating>(b, x => x.RevieweeId); LinkUser<Report>(b, x => x.ReporterId); LinkUser<Report>(b, x => x.ReportedUserId); LinkUser<Report>(b,x=>x.AssignedModeratorId); LinkUser<Notification>(b, x => x.UserId); LinkUser<QrToken>(b,x=>x.OwnerId); LinkUser<AuditEvent>(b, x => x.ActorId); LinkUser<UserBlock>(b,x=>x.BlockerId); LinkUser<UserBlock>(b,x=>x.BlockedId); LinkUser<ModerationRecord>(b,x=>x.ActorId);
  SeedTaxonomy(b);
 }
 private static void SeedTaxonomy(ModelBuilder b) { var created=new DateTime(2026,1,1,0,0,0,DateTimeKind.Utc); var categories=new[]{("11111111-1111-1111-1111-111111111111","keys"),("22222222-2222-2222-2222-222222222222","documents"),("33333333-3333-3333-3333-333333333333","bags"),("44444444-4444-4444-4444-444444444444","electronics"),("55555555-5555-5555-5555-555555555555","animals"),("66666666-6666-6666-6666-666666666666","people"),("77777777-7777-7777-7777-777777777777","wallets"),("88888888-8888-8888-8888-888888888888","other")}; b.Entity<Category>().HasData(categories.Select((x,i)=>new Category{Id=Guid.Parse(x.Item1),Slug=x.Item2,NameKey=$"category.{x.Item2}",SortOrder=i,CreatedAtUtc=created})); var subs=new[]{("aaaaaaaa-0000-0000-0000-000000000001",categories[0].Item1,"car-key"),("aaaaaaaa-0000-0000-0000-000000000002",categories[0].Item1,"house-key"),("aaaaaaaa-0000-0000-0000-000000000003",categories[1].Item1,"passport"),("aaaaaaaa-0000-0000-0000-000000000004",categories[1].Item1,"id-card"),("aaaaaaaa-0000-0000-0000-000000000005",categories[3].Item1,"mobile-phone"),("aaaaaaaa-0000-0000-0000-000000000006",categories[3].Item1,"laptop"),("aaaaaaaa-0000-0000-0000-000000000007",categories[2].Item1,"backpack"),("aaaaaaaa-0000-0000-0000-000000000008",categories[6].Item1,"card-wallet")}; b.Entity<Subcategory>().HasData(subs.Select(x=>new Subcategory{Id=Guid.Parse(x.Item1),CategoryId=Guid.Parse(x.Item2),Slug=x.Item3,NameKey=$"subcategory.{x.Item3}",CreatedAtUtc=created})); }
 private static void LinkUser<TEntity>(ModelBuilder b, Expression<Func<TEntity, object?>> key) where TEntity : class => b.Entity<TEntity>().HasOne<ApplicationUser>().WithMany().HasForeignKey(key).OnDelete(DeleteBehavior.Restrict);
}
