--
-- PostgreSQL database dump
--

\restrict SUJSnBJXu1l6PksMqYcoU3rO059CkYECFv2yyfjuuyAfACecB2uclyqosqqJZLd

-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL
);


--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL
);


--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUsers" (
    "Id" uuid NOT NULL,
    "AccountType" integer NOT NULL,
    "FirstName" text,
    "LastName" text,
    "OrganizationName" text,
    "IdentificationCiphertext" text,
    "Language" text NOT NULL,
    "Theme" text NOT NULL,
    "NotificationsEnabled" boolean NOT NULL,
    "IsSuspended" boolean NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "AllowContactSharing" boolean DEFAULT false NOT NULL,
    "EmailNotificationsEnabled" boolean DEFAULT false NOT NULL,
    "InAppNotificationsEnabled" boolean DEFAULT false NOT NULL,
    "ProfilePhotoKey" text,
    "ResponsiblePerson" text,
    "IsPermanentlyBlocked" boolean DEFAULT false NOT NULL,
    "RestrictionReasonCode" text,
    "SuspendedUntilUtc" timestamp with time zone
);


--
-- Name: AuditEvents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AuditEvents" (
    "Id" uuid NOT NULL,
    "ActorId" uuid,
    "Action" text NOT NULL,
    "EntityType" text NOT NULL,
    "EntityId" uuid,
    "MetadataJson" text NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: Categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Categories" (
    "Id" uuid NOT NULL,
    "Slug" text NOT NULL,
    "NameKey" text NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: ClaimAnswers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ClaimAnswers" (
    "Id" uuid NOT NULL,
    "ClaimId" uuid NOT NULL,
    "QuestionId" uuid NOT NULL,
    "AnswerCiphertext" text NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "QuestionSnapshot" text DEFAULT ''::text NOT NULL
);


--
-- Name: ClaimQuestions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ClaimQuestions" (
    "Id" uuid NOT NULL,
    "ItemId" uuid NOT NULL,
    "Prompt" text NOT NULL,
    "ExpectedAnswerHash" text NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "IsActive" boolean DEFAULT true NOT NULL,
    "SortOrder" integer DEFAULT 0 NOT NULL
);


--
-- Name: Claims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Claims" (
    "Id" uuid NOT NULL,
    "ItemId" uuid NOT NULL,
    "ClaimantId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "CompletedAtUtc" timestamp with time zone,
    "ConcurrencyToken" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "ReviewedAtUtc" timestamp with time zone
);


--
-- Name: ConversationParticipants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ConversationParticipants" (
    "Id" uuid NOT NULL,
    "ConversationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "LastReadAtUtc" timestamp with time zone,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: Conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Conversations" (
    "Id" uuid NOT NULL,
    "ItemId" uuid,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "DirectKey" text
);


--
-- Name: Exchanges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Exchanges" (
    "Id" uuid NOT NULL,
    "ClaimId" uuid NOT NULL,
    "CodeHash" text NOT NULL,
    "ExpiresAtUtc" timestamp with time zone,
    "CompletedAtUtc" timestamp with time zone,
    "FailedAttempts" integer NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "ClaimantId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "CodeIssuedAtUtc" timestamp with time zone,
    "CodeSalt" text DEFAULT ''::text NOT NULL,
    "ConcurrencyToken" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "GenerationCount" integer DEFAULT 0 NOT NULL,
    "ItemId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "LockedUntilUtc" timestamp with time zone,
    "OwnerId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "Status" integer DEFAULT 0 NOT NULL
);


--
-- Name: Favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Favorites" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ItemId" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: ItemAttributes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ItemAttributes" (
    "Id" uuid NOT NULL,
    "ItemId" uuid NOT NULL,
    "Key" text NOT NULL,
    "Value" text NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: ItemMatches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ItemMatches" (
    "Id" uuid NOT NULL,
    "LostItemId" uuid NOT NULL,
    "FoundItemId" uuid NOT NULL,
    "MatchScore" numeric(5,2) NOT NULL,
    "Status" integer NOT NULL,
    "NotifiedAtUtc" timestamp with time zone,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "ConcurrencyToken" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "EngineVersion" text DEFAULT ''::text NOT NULL,
    "NotificationVersion" text,
    "ScoreBreakdownJson" text DEFAULT ''::text NOT NULL
);


--
-- Name: ItemPhotos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ItemPhotos" (
    "Id" uuid NOT NULL,
    "ItemId" uuid NOT NULL,
    "StorageKey" text NOT NULL,
    "ContentType" text NOT NULL,
    "SizeBytes" bigint NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: Items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Items" (
    "Id" uuid NOT NULL,
    "OwnerId" uuid NOT NULL,
    "CategoryId" uuid NOT NULL,
    "SubcategoryId" uuid,
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Brand" text,
    "Color" text,
    "Location" text NOT NULL,
    "Latitude" double precision,
    "Longitude" double precision,
    "OccurredAtUtc" timestamp with time zone NOT NULL,
    "RewardAmount" numeric(12,2),
    "ViewCount" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: MatchingJobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."MatchingJobs" (
    "Id" uuid NOT NULL,
    "ItemId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "AttemptCount" integer NOT NULL,
    "NextAttemptAtUtc" timestamp with time zone NOT NULL,
    "LockedAtUtc" timestamp with time zone,
    "EngineVersion" text NOT NULL,
    "LastErrorCode" text,
    "ConcurrencyToken" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: Messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Messages" (
    "Id" uuid NOT NULL,
    "ConversationId" uuid NOT NULL,
    "SenderId" uuid NOT NULL,
    "Body" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: ModerationRecords; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ModerationRecords" (
    "Id" uuid NOT NULL,
    "TargetType" text NOT NULL,
    "TargetId" uuid NOT NULL,
    "Outcome" integer NOT NULL,
    "ReasonCode" text NOT NULL,
    "PolicyVersion" text NOT NULL,
    "ActorId" uuid,
    "InternalNotes" text,
    "CorrelationId" text NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: Notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Notifications" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" text NOT NULL,
    "PayloadJson" text NOT NULL,
    "ReadAtUtc" timestamp with time zone,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: QrScans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."QrScans" (
    "Id" uuid NOT NULL,
    "QrTokenId" uuid NOT NULL,
    "CoarseLocation" text,
    "ContactRequested" boolean NOT NULL,
    "UserAgentFamily" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: QrTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."QrTokens" (
    "Id" uuid NOT NULL,
    "ItemId" uuid,
    "PublicTokenHash" text NOT NULL,
    "RevokedAtUtc" timestamp with time zone,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "Description" text,
    "IsActive" boolean DEFAULT true NOT NULL,
    "Label" text DEFAULT ''::text NOT NULL,
    "OwnerId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL
);


--
-- Name: Ratings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Ratings" (
    "Id" uuid NOT NULL,
    "ExchangeId" uuid NOT NULL,
    "ReviewerId" uuid NOT NULL,
    "RevieweeId" uuid NOT NULL,
    "Score" integer NOT NULL,
    "Review" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    CONSTRAINT "CK_Ratings_Score" CHECK ((("Score" >= 1) AND ("Score" <= 5)))
);


--
-- Name: RefreshTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TokenHash" text NOT NULL,
    "ExpiresAtUtc" timestamp with time zone NOT NULL,
    "RevokedAtUtc" timestamp with time zone,
    "ReplacedByTokenId" uuid,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: Reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Reports" (
    "Id" uuid NOT NULL,
    "ReporterId" uuid NOT NULL,
    "ItemId" uuid,
    "ReportedUserId" uuid,
    "MessageId" uuid,
    "Reason" text NOT NULL,
    "Details" text,
    "Status" integer NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "AssignedModeratorId" uuid,
    "ConcurrencyToken" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "InternalNotes" text,
    "Severity" text DEFAULT ''::text NOT NULL
);


--
-- Name: Subcategories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Subcategories" (
    "Id" uuid NOT NULL,
    "CategoryId" uuid NOT NULL,
    "Slug" text NOT NULL,
    "NameKey" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone
);


--
-- Name: UserBlocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."UserBlocks" (
    "Id" uuid NOT NULL,
    "BlockerId" uuid NOT NULL,
    "BlockedId" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    CONSTRAINT "CK_UserBlocks_DifferentUsers" CHECK (("BlockerId" <> "BlockedId"))
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: AuditEvents PK_AuditEvents; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AuditEvents"
    ADD CONSTRAINT "PK_AuditEvents" PRIMARY KEY ("Id");


--
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- Name: ClaimAnswers PK_ClaimAnswers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ClaimAnswers"
    ADD CONSTRAINT "PK_ClaimAnswers" PRIMARY KEY ("Id");


--
-- Name: ClaimQuestions PK_ClaimQuestions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ClaimQuestions"
    ADD CONSTRAINT "PK_ClaimQuestions" PRIMARY KEY ("Id");


--
-- Name: Claims PK_Claims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Claims"
    ADD CONSTRAINT "PK_Claims" PRIMARY KEY ("Id");


--
-- Name: ConversationParticipants PK_ConversationParticipants; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ConversationParticipants"
    ADD CONSTRAINT "PK_ConversationParticipants" PRIMARY KEY ("Id");


--
-- Name: Conversations PK_Conversations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Conversations"
    ADD CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id");


--
-- Name: Exchanges PK_Exchanges; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Exchanges"
    ADD CONSTRAINT "PK_Exchanges" PRIMARY KEY ("Id");


--
-- Name: Favorites PK_Favorites; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "PK_Favorites" PRIMARY KEY ("Id");


--
-- Name: ItemAttributes PK_ItemAttributes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ItemAttributes"
    ADD CONSTRAINT "PK_ItemAttributes" PRIMARY KEY ("Id");


--
-- Name: ItemMatches PK_ItemMatches; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ItemMatches"
    ADD CONSTRAINT "PK_ItemMatches" PRIMARY KEY ("Id");


--
-- Name: ItemPhotos PK_ItemPhotos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ItemPhotos"
    ADD CONSTRAINT "PK_ItemPhotos" PRIMARY KEY ("Id");


--
-- Name: Items PK_Items; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "PK_Items" PRIMARY KEY ("Id");


--
-- Name: MatchingJobs PK_MatchingJobs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MatchingJobs"
    ADD CONSTRAINT "PK_MatchingJobs" PRIMARY KEY ("Id");


--
-- Name: Messages PK_Messages; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT "PK_Messages" PRIMARY KEY ("Id");


--
-- Name: ModerationRecords PK_ModerationRecords; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ModerationRecords"
    ADD CONSTRAINT "PK_ModerationRecords" PRIMARY KEY ("Id");


--
-- Name: Notifications PK_Notifications; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id");


--
-- Name: QrScans PK_QrScans; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."QrScans"
    ADD CONSTRAINT "PK_QrScans" PRIMARY KEY ("Id");


--
-- Name: QrTokens PK_QrTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."QrTokens"
    ADD CONSTRAINT "PK_QrTokens" PRIMARY KEY ("Id");


--
-- Name: Ratings PK_Ratings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Ratings"
    ADD CONSTRAINT "PK_Ratings" PRIMARY KEY ("Id");


--
-- Name: RefreshTokens PK_RefreshTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RefreshTokens"
    ADD CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id");


--
-- Name: Reports PK_Reports; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Reports"
    ADD CONSTRAINT "PK_Reports" PRIMARY KEY ("Id");


--
-- Name: Subcategories PK_Subcategories; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Subcategories"
    ADD CONSTRAINT "PK_Subcategories" PRIMARY KEY ("Id");


--
-- Name: UserBlocks PK_UserBlocks; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserBlocks"
    ADD CONSTRAINT "PK_UserBlocks" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_AuditEvents_ActorId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AuditEvents_ActorId" ON public."AuditEvents" USING btree ("ActorId");


--
-- Name: IX_AuditEvents_EntityType_EntityId_CreatedAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AuditEvents_EntityType_EntityId_CreatedAtUtc" ON public."AuditEvents" USING btree ("EntityType", "EntityId", "CreatedAtUtc");


--
-- Name: IX_Categories_Slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Categories_Slug" ON public."Categories" USING btree ("Slug");


--
-- Name: IX_ClaimAnswers_ClaimId_QuestionId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ClaimAnswers_ClaimId_QuestionId" ON public."ClaimAnswers" USING btree ("ClaimId", "QuestionId");


--
-- Name: IX_ClaimAnswers_QuestionId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ClaimAnswers_QuestionId" ON public."ClaimAnswers" USING btree ("QuestionId");


--
-- Name: IX_ClaimQuestions_ItemId_SortOrder; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ClaimQuestions_ItemId_SortOrder" ON public."ClaimQuestions" USING btree ("ItemId", "SortOrder");


--
-- Name: IX_Claims_ClaimantId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Claims_ClaimantId" ON public."Claims" USING btree ("ClaimantId");


--
-- Name: IX_Claims_ItemId_ClaimantId_Status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Claims_ItemId_ClaimantId_Status" ON public."Claims" USING btree ("ItemId", "ClaimantId", "Status");


--
-- Name: IX_ConversationParticipants_ConversationId_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ConversationParticipants_ConversationId_UserId" ON public."ConversationParticipants" USING btree ("ConversationId", "UserId");


--
-- Name: IX_ConversationParticipants_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ConversationParticipants_UserId" ON public."ConversationParticipants" USING btree ("UserId");


--
-- Name: IX_Conversations_DirectKey; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Conversations_DirectKey" ON public."Conversations" USING btree ("DirectKey");


--
-- Name: IX_Conversations_ItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Conversations_ItemId" ON public."Conversations" USING btree ("ItemId");


--
-- Name: IX_Exchanges_ClaimId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Exchanges_ClaimId" ON public."Exchanges" USING btree ("ClaimId");


--
-- Name: IX_Exchanges_ClaimantId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Exchanges_ClaimantId" ON public."Exchanges" USING btree ("ClaimantId");


--
-- Name: IX_Exchanges_ItemId_Status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Exchanges_ItemId_Status" ON public."Exchanges" USING btree ("ItemId", "Status");


--
-- Name: IX_Exchanges_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Exchanges_OwnerId" ON public."Exchanges" USING btree ("OwnerId");


--
-- Name: IX_Favorites_ItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Favorites_ItemId" ON public."Favorites" USING btree ("ItemId");


--
-- Name: IX_Favorites_UserId_ItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Favorites_UserId_ItemId" ON public."Favorites" USING btree ("UserId", "ItemId");


--
-- Name: IX_ItemAttributes_ItemId_Key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ItemAttributes_ItemId_Key" ON public."ItemAttributes" USING btree ("ItemId", "Key");


--
-- Name: IX_ItemMatches_FoundItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ItemMatches_FoundItemId" ON public."ItemMatches" USING btree ("FoundItemId");


--
-- Name: IX_ItemMatches_LostItemId_FoundItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ItemMatches_LostItemId_FoundItemId" ON public."ItemMatches" USING btree ("LostItemId", "FoundItemId");


--
-- Name: IX_ItemMatches_Status_MatchScore_UpdatedAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ItemMatches_Status_MatchScore_UpdatedAtUtc" ON public."ItemMatches" USING btree ("Status", "MatchScore", "UpdatedAtUtc");


--
-- Name: IX_ItemPhotos_ItemId_SortOrder; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ItemPhotos_ItemId_SortOrder" ON public."ItemPhotos" USING btree ("ItemId", "SortOrder");


--
-- Name: IX_Items_Brand; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Items_Brand" ON public."Items" USING btree ("Brand");


--
-- Name: IX_Items_CategoryId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Items_CategoryId" ON public."Items" USING btree ("CategoryId");


--
-- Name: IX_Items_Color; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Items_Color" ON public."Items" USING btree ("Color");


--
-- Name: IX_Items_Latitude_Longitude; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Items_Latitude_Longitude" ON public."Items" USING btree ("Latitude", "Longitude");


--
-- Name: IX_Items_OccurredAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Items_OccurredAtUtc" ON public."Items" USING btree ("OccurredAtUtc");


--
-- Name: IX_Items_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Items_OwnerId" ON public."Items" USING btree ("OwnerId");


--
-- Name: IX_Items_SubcategoryId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Items_SubcategoryId" ON public."Items" USING btree ("SubcategoryId");


--
-- Name: IX_Items_Type_Status_CreatedAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Items_Type_Status_CreatedAtUtc" ON public."Items" USING btree ("Type", "Status", "CreatedAtUtc");


--
-- Name: IX_MatchingJobs_ItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_MatchingJobs_ItemId" ON public."MatchingJobs" USING btree ("ItemId");


--
-- Name: IX_MatchingJobs_Status_NextAttemptAtUtc_LockedAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_MatchingJobs_Status_NextAttemptAtUtc_LockedAtUtc" ON public."MatchingJobs" USING btree ("Status", "NextAttemptAtUtc", "LockedAtUtc");


--
-- Name: IX_Messages_ConversationId_CreatedAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Messages_ConversationId_CreatedAtUtc" ON public."Messages" USING btree ("ConversationId", "CreatedAtUtc");


--
-- Name: IX_Messages_SenderId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Messages_SenderId" ON public."Messages" USING btree ("SenderId");


--
-- Name: IX_ModerationRecords_ActorId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ModerationRecords_ActorId" ON public."ModerationRecords" USING btree ("ActorId");


--
-- Name: IX_ModerationRecords_Outcome_CreatedAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ModerationRecords_Outcome_CreatedAtUtc" ON public."ModerationRecords" USING btree ("Outcome", "CreatedAtUtc");


--
-- Name: IX_ModerationRecords_TargetType_TargetId_CreatedAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ModerationRecords_TargetType_TargetId_CreatedAtUtc" ON public."ModerationRecords" USING btree ("TargetType", "TargetId", "CreatedAtUtc");


--
-- Name: IX_Notifications_UserId_ReadAtUtc_CreatedAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Notifications_UserId_ReadAtUtc_CreatedAtUtc" ON public."Notifications" USING btree ("UserId", "ReadAtUtc", "CreatedAtUtc");


--
-- Name: IX_QrScans_QrTokenId_CreatedAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_QrScans_QrTokenId_CreatedAtUtc" ON public."QrScans" USING btree ("QrTokenId", "CreatedAtUtc");


--
-- Name: IX_QrTokens_ItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_QrTokens_ItemId" ON public."QrTokens" USING btree ("ItemId");


--
-- Name: IX_QrTokens_OwnerId_IsActive; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_QrTokens_OwnerId_IsActive" ON public."QrTokens" USING btree ("OwnerId", "IsActive");


--
-- Name: IX_QrTokens_PublicTokenHash; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_QrTokens_PublicTokenHash" ON public."QrTokens" USING btree ("PublicTokenHash");


--
-- Name: IX_Ratings_ExchangeId_ReviewerId_RevieweeId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Ratings_ExchangeId_ReviewerId_RevieweeId" ON public."Ratings" USING btree ("ExchangeId", "ReviewerId", "RevieweeId");


--
-- Name: IX_Ratings_RevieweeId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Ratings_RevieweeId" ON public."Ratings" USING btree ("RevieweeId");


--
-- Name: IX_Ratings_ReviewerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Ratings_ReviewerId" ON public."Ratings" USING btree ("ReviewerId");


--
-- Name: IX_RefreshTokens_TokenHash; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_RefreshTokens_TokenHash" ON public."RefreshTokens" USING btree ("TokenHash");


--
-- Name: IX_RefreshTokens_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RefreshTokens_UserId" ON public."RefreshTokens" USING btree ("UserId");


--
-- Name: IX_Reports_AssignedModeratorId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Reports_AssignedModeratorId" ON public."Reports" USING btree ("AssignedModeratorId");


--
-- Name: IX_Reports_ItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Reports_ItemId" ON public."Reports" USING btree ("ItemId");


--
-- Name: IX_Reports_MessageId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Reports_MessageId" ON public."Reports" USING btree ("MessageId");


--
-- Name: IX_Reports_ReportedUserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Reports_ReportedUserId" ON public."Reports" USING btree ("ReportedUserId");


--
-- Name: IX_Reports_ReporterId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Reports_ReporterId" ON public."Reports" USING btree ("ReporterId");


--
-- Name: IX_Reports_Status_Severity_CreatedAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Reports_Status_Severity_CreatedAtUtc" ON public."Reports" USING btree ("Status", "Severity", "CreatedAtUtc");


--
-- Name: IX_Subcategories_CategoryId_Slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Subcategories_CategoryId_Slug" ON public."Subcategories" USING btree ("CategoryId", "Slug");


--
-- Name: IX_UserBlocks_BlockedId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserBlocks_BlockedId" ON public."UserBlocks" USING btree ("BlockedId");


--
-- Name: IX_UserBlocks_BlockerId_BlockedId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_UserBlocks_BlockerId_BlockedId" ON public."UserBlocks" USING btree ("BlockerId", "BlockedId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AuditEvents FK_AuditEvents_AspNetUsers_ActorId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AuditEvents"
    ADD CONSTRAINT "FK_AuditEvents_AspNetUsers_ActorId" FOREIGN KEY ("ActorId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: ClaimAnswers FK_ClaimAnswers_ClaimQuestions_QuestionId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ClaimAnswers"
    ADD CONSTRAINT "FK_ClaimAnswers_ClaimQuestions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES public."ClaimQuestions"("Id") ON DELETE RESTRICT;


--
-- Name: ClaimAnswers FK_ClaimAnswers_Claims_ClaimId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ClaimAnswers"
    ADD CONSTRAINT "FK_ClaimAnswers_Claims_ClaimId" FOREIGN KEY ("ClaimId") REFERENCES public."Claims"("Id") ON DELETE RESTRICT;


--
-- Name: ClaimQuestions FK_ClaimQuestions_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ClaimQuestions"
    ADD CONSTRAINT "FK_ClaimQuestions_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE RESTRICT;


--
-- Name: Claims FK_Claims_AspNetUsers_ClaimantId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Claims"
    ADD CONSTRAINT "FK_Claims_AspNetUsers_ClaimantId" FOREIGN KEY ("ClaimantId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Claims FK_Claims_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Claims"
    ADD CONSTRAINT "FK_Claims_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE RESTRICT;


--
-- Name: ConversationParticipants FK_ConversationParticipants_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ConversationParticipants"
    ADD CONSTRAINT "FK_ConversationParticipants_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: ConversationParticipants FK_ConversationParticipants_Conversations_ConversationId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ConversationParticipants"
    ADD CONSTRAINT "FK_ConversationParticipants_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES public."Conversations"("Id") ON DELETE CASCADE;


--
-- Name: Conversations FK_Conversations_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Conversations"
    ADD CONSTRAINT "FK_Conversations_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id");


--
-- Name: Exchanges FK_Exchanges_AspNetUsers_ClaimantId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Exchanges"
    ADD CONSTRAINT "FK_Exchanges_AspNetUsers_ClaimantId" FOREIGN KEY ("ClaimantId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Exchanges FK_Exchanges_AspNetUsers_OwnerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Exchanges"
    ADD CONSTRAINT "FK_Exchanges_AspNetUsers_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Exchanges FK_Exchanges_Claims_ClaimId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Exchanges"
    ADD CONSTRAINT "FK_Exchanges_Claims_ClaimId" FOREIGN KEY ("ClaimId") REFERENCES public."Claims"("Id") ON DELETE RESTRICT;


--
-- Name: Exchanges FK_Exchanges_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Exchanges"
    ADD CONSTRAINT "FK_Exchanges_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE RESTRICT;


--
-- Name: Favorites FK_Favorites_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "FK_Favorites_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Favorites FK_Favorites_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Favorites"
    ADD CONSTRAINT "FK_Favorites_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE RESTRICT;


--
-- Name: ItemAttributes FK_ItemAttributes_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ItemAttributes"
    ADD CONSTRAINT "FK_ItemAttributes_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE CASCADE;


--
-- Name: ItemMatches FK_ItemMatches_Items_FoundItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ItemMatches"
    ADD CONSTRAINT "FK_ItemMatches_Items_FoundItemId" FOREIGN KEY ("FoundItemId") REFERENCES public."Items"("Id") ON DELETE RESTRICT;


--
-- Name: ItemMatches FK_ItemMatches_Items_LostItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ItemMatches"
    ADD CONSTRAINT "FK_ItemMatches_Items_LostItemId" FOREIGN KEY ("LostItemId") REFERENCES public."Items"("Id") ON DELETE RESTRICT;


--
-- Name: ItemPhotos FK_ItemPhotos_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ItemPhotos"
    ADD CONSTRAINT "FK_ItemPhotos_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE CASCADE;


--
-- Name: Items FK_Items_AspNetUsers_OwnerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_AspNetUsers_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Items FK_Items_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE RESTRICT;


--
-- Name: Items FK_Items_Subcategories_SubcategoryId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_Subcategories_SubcategoryId" FOREIGN KEY ("SubcategoryId") REFERENCES public."Subcategories"("Id") ON DELETE RESTRICT;


--
-- Name: MatchingJobs FK_MatchingJobs_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MatchingJobs"
    ADD CONSTRAINT "FK_MatchingJobs_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE RESTRICT;


--
-- Name: Messages FK_Messages_AspNetUsers_SenderId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT "FK_Messages_AspNetUsers_SenderId" FOREIGN KEY ("SenderId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Messages FK_Messages_Conversations_ConversationId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES public."Conversations"("Id") ON DELETE RESTRICT;


--
-- Name: ModerationRecords FK_ModerationRecords_AspNetUsers_ActorId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ModerationRecords"
    ADD CONSTRAINT "FK_ModerationRecords_AspNetUsers_ActorId" FOREIGN KEY ("ActorId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Notifications FK_Notifications_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: QrScans FK_QrScans_QrTokens_QrTokenId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."QrScans"
    ADD CONSTRAINT "FK_QrScans_QrTokens_QrTokenId" FOREIGN KEY ("QrTokenId") REFERENCES public."QrTokens"("Id") ON DELETE RESTRICT;


--
-- Name: QrTokens FK_QrTokens_AspNetUsers_OwnerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."QrTokens"
    ADD CONSTRAINT "FK_QrTokens_AspNetUsers_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: QrTokens FK_QrTokens_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."QrTokens"
    ADD CONSTRAINT "FK_QrTokens_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE RESTRICT;


--
-- Name: Ratings FK_Ratings_AspNetUsers_RevieweeId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Ratings"
    ADD CONSTRAINT "FK_Ratings_AspNetUsers_RevieweeId" FOREIGN KEY ("RevieweeId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Ratings FK_Ratings_AspNetUsers_ReviewerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Ratings"
    ADD CONSTRAINT "FK_Ratings_AspNetUsers_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Ratings FK_Ratings_Exchanges_ExchangeId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Ratings"
    ADD CONSTRAINT "FK_Ratings_Exchanges_ExchangeId" FOREIGN KEY ("ExchangeId") REFERENCES public."Exchanges"("Id") ON DELETE CASCADE;


--
-- Name: RefreshTokens FK_RefreshTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RefreshTokens"
    ADD CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Reports FK_Reports_AspNetUsers_AssignedModeratorId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Reports"
    ADD CONSTRAINT "FK_Reports_AspNetUsers_AssignedModeratorId" FOREIGN KEY ("AssignedModeratorId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Reports FK_Reports_AspNetUsers_ReportedUserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Reports"
    ADD CONSTRAINT "FK_Reports_AspNetUsers_ReportedUserId" FOREIGN KEY ("ReportedUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Reports FK_Reports_AspNetUsers_ReporterId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Reports"
    ADD CONSTRAINT "FK_Reports_AspNetUsers_ReporterId" FOREIGN KEY ("ReporterId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Reports FK_Reports_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Reports"
    ADD CONSTRAINT "FK_Reports_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE RESTRICT;


--
-- Name: Reports FK_Reports_Messages_MessageId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Reports"
    ADD CONSTRAINT "FK_Reports_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES public."Messages"("Id") ON DELETE RESTRICT;


--
-- Name: Subcategories FK_Subcategories_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Subcategories"
    ADD CONSTRAINT "FK_Subcategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- Name: UserBlocks FK_UserBlocks_AspNetUsers_BlockedId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserBlocks"
    ADD CONSTRAINT "FK_UserBlocks_AspNetUsers_BlockedId" FOREIGN KEY ("BlockedId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: UserBlocks FK_UserBlocks_AspNetUsers_BlockerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserBlocks"
    ADD CONSTRAINT "FK_UserBlocks_AspNetUsers_BlockerId" FOREIGN KEY ("BlockerId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict SUJSnBJXu1l6PksMqYcoU3rO059CkYECFv2yyfjuuyAfACecB2uclyqosqqJZLd

